/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;

import org.ricardocolindres.controlador.ControlDeTelefono;
import org.ricardocolindres.modelo.Telefono;

/**
 *
 * @author colin
 */
public class VistaActualizarTelefono extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaActualizarTelefono
     */
    public VistaActualizarTelefono() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarTelefono = new javax.swing.JPanel();
        lblAgregarTPersonal = new javax.swing.JLabel();
        txtAgregarTPersonal = new javax.swing.JTextField();
        btnAgregarTelefono = new javax.swing.JToggleButton();
        lblAgregartLaboral = new javax.swing.JLabel();
        txtAgregartLaboral = new javax.swing.JTextField();
        separadorAgregarTelefono = new javax.swing.JSeparator();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        lblAgregarTPersonal.setText("Ingresar Telefono Personal");

        btnAgregarTelefono.setText("Actualizar Telefono");
        btnAgregarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTelefonoActionPerformed(evt);
            }
        });

        lblAgregartLaboral.setText("Ingresar Telefono  Laboral");

        javax.swing.GroupLayout panelAgregarTelefonoLayout = new javax.swing.GroupLayout(panelAgregarTelefono);
        panelAgregarTelefono.setLayout(panelAgregarTelefonoLayout);
        panelAgregarTelefonoLayout.setHorizontalGroup(
            panelAgregarTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarTelefonoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarTelefonoLayout.createSequentialGroup()
                        .addComponent(separadorAgregarTelefono)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarTelefonoLayout.createSequentialGroup()
                        .addGroup(panelAgregarTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAgregarTelefonoLayout.createSequentialGroup()
                                .addComponent(lblAgregarTPersonal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarTPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAgregarTelefonoLayout.createSequentialGroup()
                                .addComponent(lblAgregartLaboral)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(txtAgregartLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
            .addGroup(panelAgregarTelefonoLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnAgregarTelefono)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelAgregarTelefonoLayout.setVerticalGroup(
            panelAgregarTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarTelefonoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelAgregarTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarTPersonal)
                    .addComponent(txtAgregarTPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panelAgregarTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregartLaboral)
                    .addComponent(txtAgregartLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarTelefono)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTelefonoActionPerformed
        // TODO add your handling code here:
        Telefono servicio = new Telefono();
        servicio.setTelefonoPer(txtAgregarTPersonal.getText());
        servicio.setTelefonoLab(txtAgregartLaboral.getText());
        servicio.setEstadoTelefono(true);

        ControlDeTelefono controlador = new ControlDeTelefono();
        controlador.actualizarTelefono(servicio);
    }//GEN-LAST:event_btnAgregarTelefonoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarTelefono;
    private javax.swing.JLabel lblAgregarTPersonal;
    private javax.swing.JLabel lblAgregartLaboral;
    private javax.swing.JPanel panelAgregarTelefono;
    private javax.swing.JSeparator separadorAgregarTelefono;
    private javax.swing.JTextField txtAgregarTPersonal;
    private javax.swing.JTextField txtAgregartLaboral;
    // End of variables declaration//GEN-END:variables
}
