/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;

import org.ricardocolindres.controlador.ControlDeServicio;
import org.ricardocolindres.modelo.Servicio;
import org.ricardocolindres.controlador.ControlDeUsuario;


/**
 *
 * @author colin
 */
public class VistaAgregarServicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaAgregarServicio
     */
    public VistaAgregarServicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarServicio = new javax.swing.JPanel();
        lblAgregarServicio = new javax.swing.JLabel();
        txtAgregarServicio = new javax.swing.JTextField();
        btnAgregarServicio = new javax.swing.JToggleButton();
        lblAgregarCostoServicio = new javax.swing.JLabel();
        txtAgregarCostoServicio = new javax.swing.JTextField();
        separadorAgregarServicio = new javax.swing.JSeparator();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        lblAgregarServicio.setText("Ingresar Servicio");

        btnAgregarServicio.setText("Guardar Servicio");
        btnAgregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarServicioActionPerformed(evt);
            }
        });

        lblAgregarCostoServicio.setText("Ingresar Costo del Servicio");

        javax.swing.GroupLayout panelAgregarServicioLayout = new javax.swing.GroupLayout(panelAgregarServicio);
        panelAgregarServicio.setLayout(panelAgregarServicioLayout);
        panelAgregarServicioLayout.setHorizontalGroup(
            panelAgregarServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarServicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarServicioLayout.createSequentialGroup()
                        .addComponent(separadorAgregarServicio)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarServicioLayout.createSequentialGroup()
                        .addGroup(panelAgregarServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAgregarServicioLayout.createSequentialGroup()
                                .addComponent(lblAgregarServicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAgregarServicioLayout.createSequentialGroup()
                                .addComponent(lblAgregarCostoServicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(txtAgregarCostoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
            .addGroup(panelAgregarServicioLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnAgregarServicio)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelAgregarServicioLayout.setVerticalGroup(
            panelAgregarServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarServicioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelAgregarServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarServicio)
                    .addComponent(txtAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panelAgregarServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarCostoServicio)
                    .addComponent(txtAgregarCostoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarServicio)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServicioActionPerformed
        // TODO add your handling code here:
        Servicio servicio = new Servicio();
        servicio.setServicio(txtAgregarServicio.getText());
        servicio.setCosto(txtAgregarCostoServicio.getText());
        servicio.setServicioEstado(true);
        
        ControlDeServicio controlador = new ControlDeServicio();
        controlador.agregarServicio(servicio);
                                            
    }//GEN-LAST:event_btnAgregarServicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarServicio;
    private javax.swing.JLabel lblAgregarCostoServicio;
    private javax.swing.JLabel lblAgregarServicio;
    private javax.swing.JPanel panelAgregarServicio;
    private javax.swing.JSeparator separadorAgregarServicio;
    private javax.swing.JTextField txtAgregarCostoServicio;
    private javax.swing.JTextField txtAgregarServicio;
    // End of variables declaration//GEN-END:variables
}
