/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.ricardocolindres.controlador.ControlDeCliente;
import org.ricardocolindres.modelo.Cliente;

/**
 *
 * @author colin
 */
public class VistaVerCliente extends javax.swing.JInternalFrame {
    private final ControlDeCliente controlador = ControlDeCliente.getInstancia();
    /**
     * Creates new form VistaVerCliente
     */
    public VistaVerCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpanel = new javax.swing.JScrollPane();
        tblCita = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        tblCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Cliente", "Nombre", "Apellido", "Email", "Telefono", "Direccion", "Usuario", "Estado"
            }
        ));
        scrollpanel.setViewportView(tblCita);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void mostrarLibrosEnTabla(){        
        int cantidadDeRegistros = controlador.cantidadDeDireccion();
        String [] encabezados = {"Id Empleado","Nombre", "Apellido","Email","Telefono","Direccion","Usuario", "Estado"};        
        DefaultTableModel cabecera = new DefaultTableModel(encabezados,cantidadDeRegistros);
        tblCita.setModel(cabecera);
        TableModel tablaDeLibros = tblCita.getModel();
        for(int i=0; i<cantidadDeRegistros; i++){
            Cliente libro = controlador.listaDeDireccions().get(i);
            tablaDeLibros.setValueAt(libro.getIdCliente(), i, 0);
            tablaDeLibros.setValueAt(libro.getNombreCli(), i, 1);
            tablaDeLibros.setValueAt(libro.getApellidoCli(), i, 2);
            tablaDeLibros.setValueAt(libro.getIdEmail(), i, 3);
            tablaDeLibros.setValueAt(libro.getTelefonoCliente(), i, 4);
            tablaDeLibros.setValueAt(libro.getDireccionCliente(), i, 5);
            tablaDeLibros.setValueAt(libro.getUsuarioCliente(), i, 6);
            tablaDeLibros.setValueAt(libro.getEstadoCliente(), i, 7);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollpanel;
    private javax.swing.JTable tblCita;
    // End of variables declaration//GEN-END:variables
}
