/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package org.ricardocolindres.vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.ricardocolindres.controlador.ControlDeDireccion;
import org.ricardocolindres.modelo.Direccion;

/**
 *
 * @author colin
 */
public class VistaVerDireccion extends javax.swing.JInternalFrame {
    private final ControlDeDireccion controlador = ControlDeDireccion.getInstancia();
    /** Creates new form VistaVerDireccion */
    public VistaVerDireccion() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelVerCitas = new javax.swing.JScrollPane();
        tblDireccion = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        tblDireccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Direccion", "Direccion", "Departamento", "Municipio", "Estado"
            }
        ));
        scrollPanelVerCitas.setViewportView(tblDireccion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelVerCitas, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelVerCitas, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarLibrosEnTabla(){        
        int cantidadDeRegistros = controlador.cantidadDeDireccion();
        String [] encabezados = {"Id Direccion","Direccion","Departamento","Municipio","Estado"};        
        DefaultTableModel cabecera = new DefaultTableModel(encabezados,cantidadDeRegistros);
        tblDireccion.setModel(cabecera);
        TableModel tablaDeLibros = tblDireccion.getModel();
        for(int i=0; i<cantidadDeRegistros; i++){
            Direccion libro = controlador.listaDeDireccions().get(i);
            tablaDeLibros.setValueAt(libro.getIdDireccion(), i, 0);
            tablaDeLibros.setValueAt(libro.getDireccion(), i, 1);
            tablaDeLibros.setValueAt(libro.getDepartamento(), i, 2);
            tablaDeLibros.setValueAt(libro.getMunicipio(), i, 3);
            tablaDeLibros.setValueAt(libro.getEstadoDireccion(), i, 4);
            
            ControlDeDireccion direccion = new ControlDeDireccion();
            direccion.enlistaDireccion();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPanelVerCitas;
    private javax.swing.JTable tblDireccion;
    // End of variables declaration//GEN-END:variables

}
