/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;

import org.ricardocolindres.modelo.Rol;
import org.ricardocolindres.controlador.ControlDeRol;
/**
 *
 * @author colin
 */
public class VistaActualizarRol extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaActualizarRol
     */
    public VistaActualizarRol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActualizarRol = new javax.swing.JPanel();
        lblActualizarRol = new javax.swing.JLabel();
        txtActualizarRol = new javax.swing.JTextField();
        separadorActualizarRol = new javax.swing.JSeparator();
        lblActualizarID = new javax.swing.JLabel();
        txtAgctualizarID = new javax.swing.JTextField();
        btnActualizarROL = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        lblActualizarRol.setText("Nombre del Rol");

        lblActualizarID.setText("ID del Rol");

        btnActualizarROL.setText("Actualizar Rol");
        btnActualizarROL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarROLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActualizarRolLayout = new javax.swing.GroupLayout(panelActualizarRol);
        panelActualizarRol.setLayout(panelActualizarRolLayout);
        panelActualizarRolLayout.setHorizontalGroup(
            panelActualizarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarRolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActualizarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelActualizarRolLayout.createSequentialGroup()
                        .addComponent(separadorActualizarRol)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarRolLayout.createSequentialGroup()
                        .addGroup(panelActualizarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelActualizarRolLayout.createSequentialGroup()
                                .addComponent(lblActualizarID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgctualizarID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelActualizarRolLayout.createSequentialGroup()
                                .addComponent(lblActualizarRol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addComponent(txtActualizarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
            .addGroup(panelActualizarRolLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnActualizarROL)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelActualizarRolLayout.setVerticalGroup(
            panelActualizarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarRolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActualizarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActualizarID)
                    .addComponent(txtAgctualizarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActualizarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActualizarRol)
                    .addComponent(txtActualizarRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separadorActualizarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizarROL)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelActualizarRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelActualizarRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarROLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarROLActionPerformed
        // TODO add your handling code here:
        Rol rol = new Rol();
        //rol.setIdRol(Integer.parseInt(txtAgregarID.getText()));
        rol.setIdRol(Integer.parseInt(txtAgctualizarID.getText()));
        rol.setRol(txtActualizarRol.getText());
        rol.setEstadoRol(true);
        
        ControlDeRol controlador = new ControlDeRol();
        controlador.actualizarRol(rol);
    }//GEN-LAST:event_btnActualizarROLActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarROL;
    private javax.swing.JLabel lblActualizarID;
    private javax.swing.JLabel lblActualizarRol;
    private javax.swing.JPanel panelActualizarRol;
    private javax.swing.JSeparator separadorActualizarRol;
    private javax.swing.JTextField txtActualizarRol;
    private javax.swing.JTextField txtAgctualizarID;
    // End of variables declaration//GEN-END:variables
}
