/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;

import org.ricardocolindres.controlador.ControlDeEmpleado;
import org.ricardocolindres.modelo.Empleado;

/**
 *
 * @author colin
 */
public class VistaAgregarEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaAgregarEmpleado
     */
    public VistaAgregarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarEmpleado = new javax.swing.JPanel();
        lblAgregarNombre = new javax.swing.JLabel();
        txtAgregarNombre = new javax.swing.JTextField();
        lblAgregarApellido = new javax.swing.JLabel();
        txtAgregarEmpleado = new javax.swing.JTextField();
        separadorAgregarEmpleado = new javax.swing.JSeparator();
        lblAgregarEmail = new javax.swing.JLabel();
        txtAgegarEmail = new javax.swing.JTextField();
        lblAgregarTelefono = new javax.swing.JLabel();
        txtAgregarUsuario = new javax.swing.JTextField();
        lblAgregarRol = new javax.swing.JLabel();
        txtAgregarTelefono = new javax.swing.JTextField();
        lblAgregarUsuario = new javax.swing.JLabel();
        txtAgregarRol = new javax.swing.JTextField();
        btnAgregarEmpleado = new javax.swing.JToggleButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        lblAgregarNombre.setText("Ingresar Nombre");

        lblAgregarApellido.setText("Ingresar Apellido");

        lblAgregarEmail.setText("ID del Email");

        lblAgregarTelefono.setText("Id del Telefono");

        lblAgregarRol.setText("Id de Rol");

        lblAgregarUsuario.setText("Id de Usuario");

        btnAgregarEmpleado.setText("Guardar Empleado");
        btnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarEmpleadoLayout = new javax.swing.GroupLayout(panelAgregarEmpleado);
        panelAgregarEmpleado.setLayout(panelAgregarEmpleadoLayout);
        panelAgregarEmpleadoLayout.setHorizontalGroup(
            panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separadorAgregarEmpleado)
            .addGroup(panelAgregarEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAgregarEmpleadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelAgregarEmpleadoLayout.createSequentialGroup()
                                    .addComponent(lblAgregarUsuario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelAgregarEmpleadoLayout.createSequentialGroup()
                                    .addComponent(lblAgregarApellido)
                                    .addGap(92, 92, 92)
                                    .addComponent(txtAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelAgregarEmpleadoLayout.createSequentialGroup()
                                .addComponent(lblAgregarNombre)
                                .addGap(94, 94, 94)
                                .addComponent(txtAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelAgregarEmpleadoLayout.createSequentialGroup()
                        .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAgregarEmpleadoLayout.createSequentialGroup()
                                .addComponent(lblAgregarEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgegarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAgregarEmpleadoLayout.createSequentialGroup()
                                .addComponent(lblAgregarTelefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAgregarEmpleadoLayout.createSequentialGroup()
                                .addComponent(lblAgregarRol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarEmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarEmpleado)
                .addGap(28, 28, 28))
        );
        panelAgregarEmpleadoLayout.setVerticalGroup(
            panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarEmpleadoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarNombre)
                    .addComponent(txtAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarApellido)
                    .addComponent(txtAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgegarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgregarEmail))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgregarTelefono)
                    .addComponent(txtAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarRol)
                    .addComponent(txtAgregarRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarUsuario)
                    .addComponent(txtAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separadorAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarEmpleado))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        // TODO add your handling code here:
        Empleado servicio = new Empleado();
        servicio.setNombre(txtAgregarNombre.getText());
        servicio.setApellido(txtAgregarEmpleado.getText());
        servicio.setIdEmail(Integer.parseInt(txtAgegarEmail.getText()));
        servicio.setIdTelefono(Integer.parseInt(txtAgregarTelefono.getText()));
        servicio.setIdRol(Integer.parseInt(txtAgregarRol.getText()));
        servicio.setIdUsuario(Integer.parseInt(txtAgregarUsuario.getText()));
        servicio.setEstadoEmpleado(true);
        
        ControlDeEmpleado controlador = new ControlDeEmpleado();
        controlador.agregarEmpleado(servicio);
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarEmpleado;
    private javax.swing.JLabel lblAgregarApellido;
    private javax.swing.JLabel lblAgregarEmail;
    private javax.swing.JLabel lblAgregarNombre;
    private javax.swing.JLabel lblAgregarRol;
    private javax.swing.JLabel lblAgregarTelefono;
    private javax.swing.JLabel lblAgregarUsuario;
    private javax.swing.JPanel panelAgregarEmpleado;
    private javax.swing.JSeparator separadorAgregarEmpleado;
    private javax.swing.JTextField txtAgegarEmail;
    private javax.swing.JTextField txtAgregarEmpleado;
    private javax.swing.JTextField txtAgregarNombre;
    private javax.swing.JTextField txtAgregarRol;
    private javax.swing.JTextField txtAgregarTelefono;
    private javax.swing.JTextField txtAgregarUsuario;
    // End of variables declaration//GEN-END:variables
}
