/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;

import org.ricardocolindres.controlador.ControlDeDoctor;
import org.ricardocolindres.modelo.Doctor;

/**
 *
 * @author colin
 */
public class VistaAgregarDoctor extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaAgregarDoctor
     */
    public VistaAgregarDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarDoctor = new javax.swing.JPanel();
        lblAgregarNombre = new javax.swing.JLabel();
        txtAgregarNombre = new javax.swing.JTextField();
        lblAgregarApellido = new javax.swing.JLabel();
        txtAgregarEmpleado = new javax.swing.JTextField();
        separadorAgregarEmpleado = new javax.swing.JSeparator();
        lblAgregarEspecialidad = new javax.swing.JLabel();
        txtAgegarEspecialidad = new javax.swing.JTextField();
        lblAgregarEmail = new javax.swing.JLabel();
        txtAgregarUsuario = new javax.swing.JTextField();
        lblAgregarTelefono = new javax.swing.JLabel();
        txtAgregarEmail = new javax.swing.JTextField();
        lblAgregarUsuario = new javax.swing.JLabel();
        txtAgregarTelefono = new javax.swing.JTextField();
        btnAgregarDoctor = new javax.swing.JToggleButton();
        lblAgregarDireccion1 = new javax.swing.JLabel();
        txtAgregarDireccion1 = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        lblAgregarNombre.setText("Ingresar Nombre");

        lblAgregarApellido.setText("Ingresar Apellido");

        lblAgregarEspecialidad.setText("Ingresar Especialidad");

        lblAgregarEmail.setText("Id del Email");

        lblAgregarTelefono.setText("Id de Telefono");

        lblAgregarUsuario.setText("Id de Usuario");

        btnAgregarDoctor.setText("Guardar Doctor");
        btnAgregarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDoctorActionPerformed(evt);
            }
        });

        lblAgregarDireccion1.setText("Id de Direccion");

        javax.swing.GroupLayout panelAgregarDoctorLayout = new javax.swing.GroupLayout(panelAgregarDoctor);
        panelAgregarDoctor.setLayout(panelAgregarDoctorLayout);
        panelAgregarDoctorLayout.setHorizontalGroup(
            panelAgregarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separadorAgregarEmpleado)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarDoctorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarDoctor)
                .addGap(28, 28, 28))
            .addGroup(panelAgregarDoctorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAgregarDoctorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelAgregarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarDoctorLayout.createSequentialGroup()
                                .addComponent(lblAgregarNombre)
                                .addGap(94, 94, 94)
                                .addComponent(txtAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAgregarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelAgregarDoctorLayout.createSequentialGroup()
                                    .addComponent(lblAgregarDireccion1)
                                    .addGap(105, 105, 105)
                                    .addComponent(txtAgregarDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelAgregarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(panelAgregarDoctorLayout.createSequentialGroup()
                                        .addComponent(lblAgregarUsuario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelAgregarDoctorLayout.createSequentialGroup()
                                        .addComponent(lblAgregarApellido)
                                        .addGap(92, 92, 92)
                                        .addComponent(txtAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panelAgregarDoctorLayout.createSequentialGroup()
                        .addGroup(panelAgregarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAgregarDoctorLayout.createSequentialGroup()
                                .addComponent(lblAgregarEspecialidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgegarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAgregarDoctorLayout.createSequentialGroup()
                                .addComponent(lblAgregarEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAgregarDoctorLayout.createSequentialGroup()
                                .addComponent(lblAgregarTelefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGap(76, 76, 76))
        );
        panelAgregarDoctorLayout.setVerticalGroup(
            panelAgregarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarDoctorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelAgregarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarNombre)
                    .addComponent(txtAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarApellido)
                    .addComponent(txtAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgegarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgregarEspecialidad))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgregarEmail)
                    .addComponent(txtAgregarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarTelefono)
                    .addComponent(txtAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(panelAgregarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarDireccion1)
                    .addComponent(txtAgregarDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgregarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarUsuario)
                    .addComponent(txtAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separadorAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarDoctor))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDoctorActionPerformed
        // TODO add your handling code here:
        Doctor servicio = new Doctor();
        servicio.setNombre(txtAgregarNombre.getText());
        servicio.setApellido(txtAgregarEmpleado.getText());
        servicio.setEspecialidad(txtAgegarEspecialidad.getText());
        servicio.setIdEmail(Integer.parseInt(txtAgregarEmail.getText()));
        servicio.setIdTelefono(Integer.parseInt(txtAgregarTelefono.getText()));
        servicio.setIdDireccion(Integer.parseInt(txtAgregarDireccion1.getText()));
        servicio.setEstadoDoctor(true);
        
        ControlDeDoctor controlador = new ControlDeDoctor();
        controlador.agregarDoctor(servicio);
    }//GEN-LAST:event_btnAgregarDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarDoctor;
    private javax.swing.JLabel lblAgregarApellido;
    private javax.swing.JLabel lblAgregarDireccion1;
    private javax.swing.JLabel lblAgregarEmail;
    private javax.swing.JLabel lblAgregarEspecialidad;
    private javax.swing.JLabel lblAgregarNombre;
    private javax.swing.JLabel lblAgregarTelefono;
    private javax.swing.JLabel lblAgregarUsuario;
    private javax.swing.JPanel panelAgregarDoctor;
    private javax.swing.JSeparator separadorAgregarEmpleado;
    private javax.swing.JTextField txtAgegarEspecialidad;
    private javax.swing.JTextField txtAgregarDireccion1;
    private javax.swing.JTextField txtAgregarEmail;
    private javax.swing.JTextField txtAgregarEmpleado;
    private javax.swing.JTextField txtAgregarNombre;
    private javax.swing.JTextField txtAgregarTelefono;
    private javax.swing.JTextField txtAgregarUsuario;
    // End of variables declaration//GEN-END:variables
}
