/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;

import org.ricardocolindres.controlador.ControlDeCita;
import org.ricardocolindres.modelo.Cita;

/**
 *
 * @author colin
 */
public class VistaAgregarCita extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaAgregarCita
     */
    public VistaAgregarCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarCita = new javax.swing.JPanel();
        lblAgregarFecha = new javax.swing.JLabel();
        txtAgregarFecha = new javax.swing.JTextField();
        lblAgregarHora = new javax.swing.JLabel();
        txtAgregarHora = new javax.swing.JTextField();
        separadorAgregarCita = new javax.swing.JSeparator();
        lblAgregarCosto = new javax.swing.JLabel();
        txtAgregartCosto = new javax.swing.JTextField();
        lblAgregarCliente = new javax.swing.JLabel();
        txtAgregarServicio = new javax.swing.JTextField();
        lblAgregarDoctor = new javax.swing.JLabel();
        txtAgregarCliente = new javax.swing.JTextField();
        lblAgregarServicio = new javax.swing.JLabel();
        txtAgregarDoctor = new javax.swing.JTextField();
        btnAgregarCita = new javax.swing.JToggleButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        lblAgregarFecha.setText("Ingresar Fecha");

        lblAgregarHora.setText("Ingresar Hora");

        lblAgregarCosto.setText("Costo Total");

        lblAgregarCliente.setText("Id del Cliente");

        lblAgregarDoctor.setText("Id del Doctor");

        lblAgregarServicio.setText("Id del Servicio");

        btnAgregarCita.setText("Guardar Cita");
        btnAgregarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarCitaLayout = new javax.swing.GroupLayout(panelAgregarCita);
        panelAgregarCita.setLayout(panelAgregarCitaLayout);
        panelAgregarCitaLayout.setHorizontalGroup(
            panelAgregarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separadorAgregarCita)
            .addGroup(panelAgregarCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarCitaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarCita)
                        .addGap(18, 18, 18))
                    .addGroup(panelAgregarCitaLayout.createSequentialGroup()
                        .addGroup(panelAgregarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarCitaLayout.createSequentialGroup()
                                .addComponent(lblAgregarFecha)
                                .addGap(87, 87, 87)
                                .addComponent(txtAgregarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAgregarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelAgregarCitaLayout.createSequentialGroup()
                                    .addComponent(lblAgregarServicio)
                                    .addGap(88, 88, 88)
                                    .addComponent(txtAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelAgregarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(panelAgregarCitaLayout.createSequentialGroup()
                                        .addComponent(lblAgregarCosto)
                                        .addGap(106, 106, 106)
                                        .addComponent(txtAgregartCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelAgregarCitaLayout.createSequentialGroup()
                                        .addComponent(lblAgregarHora)
                                        .addGap(92, 92, 92)
                                        .addComponent(txtAgregarHora, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAgregarCitaLayout.createSequentialGroup()
                                        .addComponent(lblAgregarCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAgregarCitaLayout.createSequentialGroup()
                                        .addComponent(lblAgregarDoctor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAgregarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(100, Short.MAX_VALUE))))
        );
        panelAgregarCitaLayout.setVerticalGroup(
            panelAgregarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarCitaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelAgregarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarFecha)
                    .addComponent(txtAgregarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarHora)
                    .addComponent(txtAgregarHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgregartCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgregarCosto))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgregarCliente)
                    .addComponent(txtAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarDoctor)
                    .addComponent(txtAgregarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(panelAgregarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarServicio)
                    .addComponent(txtAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separadorAgregarCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarCita))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCitaActionPerformed
        // TODO add your handling code here:
        Cita servicio = new Cita();
        servicio.setFecha(txtAgregarFecha.getText());
        servicio.setHora(txtAgregarHora.getText());
        servicio.setCosto(Integer.parseInt(txtAgregartCosto.getText()));
        servicio.setCliente(Integer.parseInt(txtAgregarCliente.getText()));
        servicio.setDoctor(Integer.parseInt(txtAgregarDoctor.getText()));
        servicio.setServicio(Integer.parseInt(txtAgregarServicio.getText()));
        servicio.setEstadoCita(true);
        
        ControlDeCita controlador = new ControlDeCita();
        controlador.agregarCita(servicio);
    }//GEN-LAST:event_btnAgregarCitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarCita;
    private javax.swing.JLabel lblAgregarCliente;
    private javax.swing.JLabel lblAgregarCosto;
    private javax.swing.JLabel lblAgregarDoctor;
    private javax.swing.JLabel lblAgregarFecha;
    private javax.swing.JLabel lblAgregarHora;
    private javax.swing.JLabel lblAgregarServicio;
    private javax.swing.JPanel panelAgregarCita;
    private javax.swing.JSeparator separadorAgregarCita;
    private javax.swing.JTextField txtAgregarCliente;
    private javax.swing.JTextField txtAgregarDoctor;
    private javax.swing.JTextField txtAgregarFecha;
    private javax.swing.JTextField txtAgregarHora;
    private javax.swing.JTextField txtAgregarServicio;
    private javax.swing.JTextField txtAgregartCosto;
    // End of variables declaration//GEN-END:variables
}
