/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;

import org.ricardocolindres.controlador.ControlDeMascota;
import org.ricardocolindres.modelo.Mascota;

/**
 *
 * @author colin
 */
public class VistaAgregarMascota extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaAgregarMascota
     */
    public VistaAgregarMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarEmpleado = new javax.swing.JPanel();
        lblAgregarNombre = new javax.swing.JLabel();
        txtAgregarNombre = new javax.swing.JTextField();
        lblAgregarEspecie = new javax.swing.JLabel();
        txtAgregarEspecie = new javax.swing.JTextField();
        separadorAgregarCliente = new javax.swing.JSeparator();
        lblAgregarRaza = new javax.swing.JLabel();
        txtAgegarRaza = new javax.swing.JTextField();
        lblAgregarEdad = new javax.swing.JLabel();
        txtAgregarCliente = new javax.swing.JTextField();
        lblAgregarGenero = new javax.swing.JLabel();
        txtAgregarEdad = new javax.swing.JTextField();
        lblAgregarCliente = new javax.swing.JLabel();
        txtAgregarGenero = new javax.swing.JTextField();
        btnAgregarMascota = new javax.swing.JToggleButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        lblAgregarNombre.setText("Ingresar Nombre");

        lblAgregarEspecie.setText("Ingresar Especie");

        lblAgregarRaza.setText("Ingresar Raza");

        lblAgregarEdad.setText("Ingresar Edad");

        lblAgregarGenero.setText("Ingresar Genero");

        lblAgregarCliente.setText("Ingresar ID Cliente");

        btnAgregarMascota.setText("Guardar Mascota");
        btnAgregarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMascotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarEmpleadoLayout = new javax.swing.GroupLayout(panelAgregarEmpleado);
        panelAgregarEmpleado.setLayout(panelAgregarEmpleadoLayout);
        panelAgregarEmpleadoLayout.setHorizontalGroup(
            panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separadorAgregarCliente)
            .addGroup(panelAgregarEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAgregarEmpleadoLayout.createSequentialGroup()
                        .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAgregarRaza, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgregarEdad, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAgregarEmpleadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAgregarEmpleadoLayout.createSequentialGroup()
                                .addComponent(lblAgregarGenero)
                                .addGap(94, 94, 94)
                                .addComponent(txtAgregarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAgegarRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarEmpleadoLayout.createSequentialGroup()
                                    .addComponent(lblAgregarCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarEmpleadoLayout.createSequentialGroup()
                                    .addComponent(lblAgregarEspecie)
                                    .addGap(92, 92, 92)
                                    .addComponent(txtAgregarEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelAgregarEmpleadoLayout.createSequentialGroup()
                                    .addComponent(lblAgregarNombre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtAgregarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarEmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarMascota)
                .addGap(28, 28, 28))
        );
        panelAgregarEmpleadoLayout.setVerticalGroup(
            panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarEmpleadoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarNombre)
                    .addComponent(txtAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarEspecie)
                    .addComponent(txtAgregarEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgegarRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgregarRaza))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarEdad)
                    .addComponent(txtAgregarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarGenero)
                    .addComponent(txtAgregarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(panelAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarCliente)
                    .addComponent(txtAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separadorAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarMascota))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMascotaActionPerformed
        // TODO add your handling code here:
        Mascota servicio = new Mascota();
        servicio.setNombre(txtAgregarNombre.getText());
        servicio.setEspecie(txtAgregarEspecie.getText());
        servicio.setRaza(txtAgegarRaza.getText());
        servicio.setEdad(txtAgregarEdad.getText());
        servicio.setGenero(txtAgregarGenero.getText());
        servicio.setClienteMascota(Integer.parseInt(txtAgregarCliente.getText()));
        servicio.setEstadoMascota(true);
        
        ControlDeMascota controlador = new ControlDeMascota();
        controlador.agregarMascota(servicio);
    }//GEN-LAST:event_btnAgregarMascotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarMascota;
    private javax.swing.JLabel lblAgregarCliente;
    private javax.swing.JLabel lblAgregarEdad;
    private javax.swing.JLabel lblAgregarEspecie;
    private javax.swing.JLabel lblAgregarGenero;
    private javax.swing.JLabel lblAgregarNombre;
    private javax.swing.JLabel lblAgregarRaza;
    private javax.swing.JPanel panelAgregarEmpleado;
    private javax.swing.JSeparator separadorAgregarCliente;
    private javax.swing.JTextField txtAgegarRaza;
    private javax.swing.JTextField txtAgregarCliente;
    private javax.swing.JTextField txtAgregarEdad;
    private javax.swing.JTextField txtAgregarEspecie;
    private javax.swing.JTextField txtAgregarGenero;
    private javax.swing.JTextField txtAgregarNombre;
    // End of variables declaration//GEN-END:variables
}
