/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import org.ricardocolindres.controlador.ControlDeCliente;
import org.ricardocolindres.modelo.Cliente;

/**
 *
 * @author colin
 */
public class VistaActualizarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaActualizarCliente
     */
    public VistaActualizarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActualizarCliente = new javax.swing.JPanel();
        lblAgregarNombre = new javax.swing.JLabel();
        txtAgregarNombre = new javax.swing.JTextField();
        lblAgregarApellido = new javax.swing.JLabel();
        txtAgregarEmpleado = new javax.swing.JTextField();
        separadorAgregarCliente = new javax.swing.JSeparator();
        lblAgregarEmail = new javax.swing.JLabel();
        txtAgegarEmail = new javax.swing.JTextField();
        lblAgregarTelefono = new javax.swing.JLabel();
        txtAgregarUsuario = new javax.swing.JTextField();
        lblAgregarDireccion = new javax.swing.JLabel();
        txtAgregarTelefono = new javax.swing.JTextField();
        lblAgregarUsuario = new javax.swing.JLabel();
        txtAgregarDireccion = new javax.swing.JTextField();
        btnAgregarDireccion = new javax.swing.JToggleButton();
        lblAgregarNombre1 = new javax.swing.JLabel();
        txtAgregarNombre1 = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        lblAgregarNombre.setText("Ingresar Nombre");

        lblAgregarApellido.setText("Ingresar Apellido");

        lblAgregarEmail.setText("ID del Email");

        lblAgregarTelefono.setText("Id del Telefono");

        lblAgregarDireccion.setText("Id de  Direccion");

        lblAgregarUsuario.setText("Id de Usuario");

        btnAgregarDireccion.setText("Actualizar Cliente");
        btnAgregarDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDireccionActionPerformed(evt);
            }
        });

        lblAgregarNombre1.setText("ID Cliente");

        javax.swing.GroupLayout panelActualizarClienteLayout = new javax.swing.GroupLayout(panelActualizarCliente);
        panelActualizarCliente.setLayout(panelActualizarClienteLayout);
        panelActualizarClienteLayout.setHorizontalGroup(
            panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separadorAgregarCliente)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarDireccion)
                .addGap(28, 28, 28))
            .addGroup(panelActualizarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelActualizarClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelActualizarClienteLayout.createSequentialGroup()
                                .addComponent(lblAgregarNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelActualizarClienteLayout.createSequentialGroup()
                                    .addComponent(lblAgregarNombre1)
                                    .addGap(140, 140, 140)
                                    .addComponent(txtAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarClienteLayout.createSequentialGroup()
                                        .addComponent(lblAgregarUsuario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarClienteLayout.createSequentialGroup()
                                        .addComponent(lblAgregarApellido)
                                        .addGap(92, 92, 92)
                                        .addComponent(txtAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panelActualizarClienteLayout.createSequentialGroup()
                        .addComponent(lblAgregarEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAgegarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelActualizarClienteLayout.createSequentialGroup()
                        .addComponent(lblAgregarTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelActualizarClienteLayout.createSequentialGroup()
                        .addComponent(lblAgregarDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAgregarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
        );
        panelActualizarClienteLayout.setVerticalGroup(
            panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarNombre1)
                    .addComponent(txtAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarNombre)
                    .addComponent(txtAgregarNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgregarApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAgregarEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgregarEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAgegarEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarTelefono)
                    .addComponent(txtAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarDireccion)
                    .addComponent(txtAgregarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarUsuario)
                    .addComponent(txtAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separadorAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarDireccion))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelActualizarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelActualizarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDireccionActionPerformed
        // TODO add your handling code here:
        Cliente servicio = new Cliente();
        servicio.setIdCliente(Integer.parseInt(txtAgregarNombre1.getText()));
        servicio.setNombreCli(txtAgregarNombre.getText());
        servicio.setApellidoCli(txtAgregarEmpleado.getText());
        servicio.setEmailCliente(Integer.parseInt(txtAgegarEmail.getText()));
        servicio.setTelefonoCliente(Integer.parseInt(txtAgregarTelefono.getText()));
        servicio.setDireccionCliente(Integer.parseInt(txtAgregarDireccion.getText()));
        servicio.setUsuarioCliente(Integer.parseInt(txtAgregarUsuario.getText()));
        servicio.setEstadoCliente(true);

        ControlDeCliente controlador = new ControlDeCliente();
        controlador.actualizarCliente(servicio);
    }//GEN-LAST:event_btnAgregarDireccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarDireccion;
    private javax.swing.JLabel lblAgregarApellido;
    private javax.swing.JLabel lblAgregarDireccion;
    private javax.swing.JLabel lblAgregarEmail;
    private javax.swing.JLabel lblAgregarNombre;
    private javax.swing.JLabel lblAgregarNombre1;
    private javax.swing.JLabel lblAgregarTelefono;
    private javax.swing.JLabel lblAgregarUsuario;
    private javax.swing.JPanel panelActualizarCliente;
    private javax.swing.JSeparator separadorAgregarCliente;
    private javax.swing.JTextField txtAgegarEmail;
    private javax.swing.JTextField txtAgregarDireccion;
    private javax.swing.JTextField txtAgregarEmpleado;
    private javax.swing.JTextField txtAgregarNombre;
    private javax.swing.JTextField txtAgregarNombre1;
    private javax.swing.JTextField txtAgregarTelefono;
    private javax.swing.JTextField txtAgregarUsuario;
    // End of variables declaration//GEN-END:variables
}
