/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;

import org.ricardocolindres.controlador.ControlDeEmail;
import org.ricardocolindres.modelo.Email;

/**
 *
 * @author colin
 */
public class VistaActualizarEmail extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaActualizarEmail
     */
    public VistaActualizarEmail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarEmail = new javax.swing.JPanel();
        lblAgregarEPersonal = new javax.swing.JLabel();
        txtAgregarEPersonal = new javax.swing.JTextField();
        btnAgregarEmail = new javax.swing.JToggleButton();
        lblAgregarELaboral = new javax.swing.JLabel();
        txtAgregarELaboral = new javax.swing.JTextField();
        separadorAgregarEmail = new javax.swing.JSeparator();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        lblAgregarEPersonal.setText("Ingresar Email Personal");

        btnAgregarEmail.setText("Actualizar Email");
        btnAgregarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmailActionPerformed(evt);
            }
        });

        lblAgregarELaboral.setText("Ingresar Email Laboral");

        javax.swing.GroupLayout panelAgregarEmailLayout = new javax.swing.GroupLayout(panelAgregarEmail);
        panelAgregarEmail.setLayout(panelAgregarEmailLayout);
        panelAgregarEmailLayout.setHorizontalGroup(
            panelAgregarEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarEmailLayout.createSequentialGroup()
                        .addComponent(separadorAgregarEmail)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarEmailLayout.createSequentialGroup()
                        .addGroup(panelAgregarEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAgregarEmailLayout.createSequentialGroup()
                                .addComponent(lblAgregarEPersonal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarEPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAgregarEmailLayout.createSequentialGroup()
                                .addComponent(lblAgregarELaboral)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(txtAgregarELaboral, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
            .addGroup(panelAgregarEmailLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnAgregarEmail)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelAgregarEmailLayout.setVerticalGroup(
            panelAgregarEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarEmailLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelAgregarEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarEPersonal)
                    .addComponent(txtAgregarEPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panelAgregarEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarELaboral)
                    .addComponent(txtAgregarELaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorAgregarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarEmail)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelAgregarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmailActionPerformed
        // TODO add your handling code here:
        Email servicio = new Email();
        servicio.setEmailPer(txtAgregarEPersonal.getText());
        servicio.setEmailLab(txtAgregarELaboral.getText());
        servicio.setEstadoEmail(true);

        ControlDeEmail controlador = new ControlDeEmail();
        controlador.actualizarEmail(servicio);
    }//GEN-LAST:event_btnAgregarEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarEmail;
    private javax.swing.JLabel lblAgregarELaboral;
    private javax.swing.JLabel lblAgregarEPersonal;
    private javax.swing.JPanel panelAgregarEmail;
    private javax.swing.JSeparator separadorAgregarEmail;
    private javax.swing.JTextField txtAgregarELaboral;
    private javax.swing.JTextField txtAgregarEPersonal;
    // End of variables declaration//GEN-END:variables
}
