/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.ricardocolindres.controlador.ControlDeTelefono;
import org.ricardocolindres.modelo.Telefono;

/**
 *
 * @author colin
 */
public class VistaVerTelefono extends javax.swing.JInternalFrame {
    private final ControlDeTelefono controlador = ControlDeTelefono.getInstancia();
    /**
     * Creates new form VistaVerTelefono
     */
    public VistaVerTelefono() {
        initComponents();
    }
     private void mostrarLibrosEnTabla(){        
        int cantidadDeRegistros = controlador.cantidadDeDireccion();
        String [] encabezados = {"Id Telefono","Telefono Personal", "Telefono Laboral", "Estado"};        
        DefaultTableModel cabecera = new DefaultTableModel(encabezados,cantidadDeRegistros);
        tblCita.setModel(cabecera);
        TableModel tablaDeLibros = tblCita.getModel();
        for(int i=0; i<cantidadDeRegistros; i++){
            Telefono libro = controlador.listaDeDireccions().get(i);
            tablaDeLibros.setValueAt(libro.getIdTelefono(), i, 0);
            tablaDeLibros.setValueAt(libro.getTelefonoPer(), i, 1);
            tablaDeLibros.setValueAt(libro.getTelefonoLab(), i, 2);
            tablaDeLibros.setValueAt(libro.getEstadoTelefono(), i, 3);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpanel = new javax.swing.JScrollPane();
        tblCita = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        tblCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Telefono", "Telefono Personal", "Telefono Laboral", "Estado"
            }
        ));
        scrollpanel.setViewportView(tblCita);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollpanel;
    private javax.swing.JTable tblCita;
    // End of variables declaration//GEN-END:variables
}
