/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import org.ricardocolindres.modelo.Rol;
import org.ricardocolindres.controlador.ControlDeRol;

/**
 *
 * @author colin
 */

class PanelDeImagen extends JPanel{
    private Image imagen; 
    public PanelDeImagen (Image imagen){
        this.imagen = imagen;
    }
    @Override 
    protected void paintComponent(Graphics grafica){
        super.paintComponent(grafica);
        grafica.drawImage(imagen ,0,0,400,300,this);
    }
}
public class VistaAgregarRol extends javax.swing.JInternalFrame {
    private Image imagenDelPanel;
    /**
     * Creates new form VistaAgregarRol
     */
    public VistaAgregarRol() {
        String direccionImagen = "/org/ricardocolindres/recurso/Login.jpg ";
        cargarImagenDelPanel(this.getClass().getResource(direccionImagen));
        initComponents();
    }
    
    private void cargarImagenDelPanel (URL nombreImagen){
        try{
            imagenDelPanel = ImageIO.read(nombreImagen);
        }catch(IOException error){
            error.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarRol = new javax.swing.JPanel();
        lblAgregarRol = new javax.swing.JLabel();
        txtAgregarRol = new javax.swing.JTextField();
        btnAgregarRol = new javax.swing.JToggleButton();
        separadorAgregarRol = new javax.swing.JSeparator();
        lblAgregarID = new javax.swing.JLabel();
        txtAgregarID = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Agregar Rol");

        lblAgregarRol.setText("Nombre del Rol");

        btnAgregarRol.setText("Guardar Rol");
        btnAgregarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRolActionPerformed(evt);
            }
        });

        lblAgregarID.setText("ID del Rol");

        javax.swing.GroupLayout panelAgregarRolLayout = new javax.swing.GroupLayout(panelAgregarRol);
        panelAgregarRol.setLayout(panelAgregarRolLayout);
        panelAgregarRolLayout.setHorizontalGroup(
            panelAgregarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarRolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarRolLayout.createSequentialGroup()
                        .addComponent(separadorAgregarRol)
                        .addContainerGap())
                    .addGroup(panelAgregarRolLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnAgregarRol)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarRolLayout.createSequentialGroup()
                        .addGroup(panelAgregarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAgregarRolLayout.createSequentialGroup()
                                .addComponent(lblAgregarID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAgregarRolLayout.createSequentialGroup()
                                .addComponent(lblAgregarRol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addComponent(txtAgregarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
        );
        panelAgregarRolLayout.setVerticalGroup(
            panelAgregarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarRolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarID)
                    .addComponent(txtAgregarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarRol)
                    .addComponent(txtAgregarRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separadorAgregarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarRol)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelAgregarRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(panelAgregarRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRolActionPerformed
        // TODO add your handling code here:
        Rol rol = new Rol();
        //rol.setIdRol(Integer.parseInt(txtAgregarID.getText()));
        rol.setIdRol(Integer.parseInt(txtAgregarID.getText()));
        rol.setRol(txtAgregarRol.getText());
        rol.setEstadoRol(true);
        
        ControlDeRol controlador = new ControlDeRol();
        controlador.agregarRol(rol);
    }//GEN-LAST:event_btnAgregarRolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarRol;
    private javax.swing.JLabel lblAgregarID;
    private javax.swing.JLabel lblAgregarRol;
    private javax.swing.JPanel panelAgregarRol;
    private javax.swing.JSeparator separadorAgregarRol;
    private javax.swing.JTextField txtAgregarID;
    private javax.swing.JTextField txtAgregarRol;
    // End of variables declaration//GEN-END:variables
}
