/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;

import org.ricardocolindres.controlador.ControlDeDoctor;
import org.ricardocolindres.modelo.Doctor;

/**
 *
 * @author colin
 */
public class VistaActualizarDoctor extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaActualizarDoctor
     */
    public VistaActualizarDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActualizarDoctor = new javax.swing.JPanel();
        lblAgregarNombre = new javax.swing.JLabel();
        txtAgregarNombre = new javax.swing.JTextField();
        lblAgregarApellido = new javax.swing.JLabel();
        txtAgregarEmpleado = new javax.swing.JTextField();
        separadorAgregarEmpleado = new javax.swing.JSeparator();
        lblAgregarEspecialidad = new javax.swing.JLabel();
        txtAgegarEspecialidad = new javax.swing.JTextField();
        lblAgregarEmail = new javax.swing.JLabel();
        txtAgregarUsuario = new javax.swing.JTextField();
        lblAgregarTelefono = new javax.swing.JLabel();
        txtAgregarEmail = new javax.swing.JTextField();
        lblAgregarUsuario = new javax.swing.JLabel();
        txtAgregarTelefono = new javax.swing.JTextField();
        btnAgregarDoctor = new javax.swing.JToggleButton();
        lblAgregarDireccion1 = new javax.swing.JLabel();
        txtAgregarDireccion1 = new javax.swing.JTextField();
        lblAgregarNombre1 = new javax.swing.JLabel();
        txtAgregarNombre1 = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        lblAgregarNombre.setText("Ingresar Nombre");

        lblAgregarApellido.setText("Ingresar Apellido");

        lblAgregarEspecialidad.setText("Ingresar Especialidad");

        lblAgregarEmail.setText("Id del Email");

        lblAgregarTelefono.setText("Id de Telefono");

        lblAgregarUsuario.setText("Id de Usuario");

        btnAgregarDoctor.setText("Actualizar Doctor");
        btnAgregarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDoctorActionPerformed(evt);
            }
        });

        lblAgregarDireccion1.setText("Id de Direccion");

        lblAgregarNombre1.setText("Ingresar Nombre");

        javax.swing.GroupLayout panelActualizarDoctorLayout = new javax.swing.GroupLayout(panelActualizarDoctor);
        panelActualizarDoctor.setLayout(panelActualizarDoctorLayout);
        panelActualizarDoctorLayout.setHorizontalGroup(
            panelActualizarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separadorAgregarEmpleado)
            .addGroup(panelActualizarDoctorLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(panelActualizarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarDoctorLayout.createSequentialGroup()
                        .addComponent(btnAgregarDoctor)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarDoctorLayout.createSequentialGroup()
                        .addGroup(panelActualizarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelActualizarDoctorLayout.createSequentialGroup()
                                .addComponent(lblAgregarEspecialidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgegarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelActualizarDoctorLayout.createSequentialGroup()
                                .addComponent(lblAgregarDireccion1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelActualizarDoctorLayout.createSequentialGroup()
                                .addComponent(lblAgregarUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelActualizarDoctorLayout.createSequentialGroup()
                                .addComponent(lblAgregarApellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelActualizarDoctorLayout.createSequentialGroup()
                                .addComponent(lblAgregarTelefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelActualizarDoctorLayout.createSequentialGroup()
                                .addComponent(lblAgregarEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelActualizarDoctorLayout.createSequentialGroup()
                                .addComponent(lblAgregarNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelActualizarDoctorLayout.createSequentialGroup()
                                .addComponent(lblAgregarNombre1)
                                .addGap(112, 112, 112)
                                .addComponent(txtAgregarNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77))))
        );
        panelActualizarDoctorLayout.setVerticalGroup(
            panelActualizarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarDoctorLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(panelActualizarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarNombre1)
                    .addComponent(txtAgregarNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgregarNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAgregarNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgregarApellido))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgegarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgregarEspecialidad))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgregarEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAgregarEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAgregarTelefono)
                    .addComponent(txtAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarDireccion1)
                    .addComponent(txtAgregarDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgregarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarDoctor))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelActualizarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelActualizarDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDoctorActionPerformed
        // TODO add your handling code here:
        Doctor servicio = new Doctor();
        servicio.setId(Integer.parseInt(txtAgregarNombre1.getText()));
        servicio.setNombre(txtAgregarNombre.getText());
        servicio.setApellido(txtAgregarEmpleado.getText());
        servicio.setEspecialidad(txtAgegarEspecialidad.getText());
        servicio.setIdEmail(Integer.parseInt(txtAgregarEmail.getText()));
        servicio.setIdTelefono(Integer.parseInt(txtAgregarTelefono.getText()));
        servicio.setIdDireccion(Integer.parseInt(txtAgregarDireccion1.getText()));
        servicio.setEstadoDoctor(true);

        ControlDeDoctor controlador = new ControlDeDoctor();
        controlador.actualizarDoctor(servicio);
    }//GEN-LAST:event_btnAgregarDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarDoctor;
    private javax.swing.JLabel lblAgregarApellido;
    private javax.swing.JLabel lblAgregarDireccion1;
    private javax.swing.JLabel lblAgregarEmail;
    private javax.swing.JLabel lblAgregarEspecialidad;
    private javax.swing.JLabel lblAgregarNombre;
    private javax.swing.JLabel lblAgregarNombre1;
    private javax.swing.JLabel lblAgregarTelefono;
    private javax.swing.JLabel lblAgregarUsuario;
    private javax.swing.JPanel panelActualizarDoctor;
    private javax.swing.JSeparator separadorAgregarEmpleado;
    private javax.swing.JTextField txtAgegarEspecialidad;
    private javax.swing.JTextField txtAgregarDireccion1;
    private javax.swing.JTextField txtAgregarEmail;
    private javax.swing.JTextField txtAgregarEmpleado;
    private javax.swing.JTextField txtAgregarNombre;
    private javax.swing.JTextField txtAgregarNombre1;
    private javax.swing.JTextField txtAgregarTelefono;
    private javax.swing.JTextField txtAgregarUsuario;
    // End of variables declaration//GEN-END:variables
}
