/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;

import org.ricardocolindres.controlador.ControlProveedor;
import org.ricardocolindres.modelo.Proveedor;

/**
 *
 * @author colin
 */
public class VistaAgregarProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaAgregarProveedor
     */
    public VistaAgregarProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarRol = new javax.swing.JPanel();
        lblAgregarProveedor = new javax.swing.JLabel();
        txtAgregarProveedor = new javax.swing.JTextField();
        btnAgregarProveedor = new javax.swing.JToggleButton();
        separadorAgregarProveedor = new javax.swing.JSeparator();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        lblAgregarProveedor.setText("Nombre del Proveedor");

        btnAgregarProveedor.setText("Guardar Proveedor");
        btnAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarRolLayout = new javax.swing.GroupLayout(panelAgregarRol);
        panelAgregarRol.setLayout(panelAgregarRolLayout);
        panelAgregarRolLayout.setHorizontalGroup(
            panelAgregarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarRolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarRolLayout.createSequentialGroup()
                        .addComponent(separadorAgregarProveedor)
                        .addContainerGap())
                    .addGroup(panelAgregarRolLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnAgregarProveedor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarRolLayout.createSequentialGroup()
                        .addComponent(lblAgregarProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(txtAgregarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        panelAgregarRolLayout.setVerticalGroup(
            panelAgregarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarRolLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelAgregarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarProveedor)
                    .addComponent(txtAgregarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separadorAgregarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarProveedor)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelAgregarRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelAgregarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProveedorActionPerformed
        // TODO add your handling code here:
        Proveedor proveedor = new Proveedor();
        //rol.setIdRol(Integer.parseInt(txtAgregarID.getText()));
        proveedor.setProveedor(txtAgregarProveedor.getText());
        proveedor.setEstado(true);

        ControlProveedor controlador = new ControlProveedor();
        controlador.agregarProveedor(proveedor);
    }//GEN-LAST:event_btnAgregarProveedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarProveedor;
    private javax.swing.JLabel lblAgregarProveedor;
    private javax.swing.JPanel panelAgregarRol;
    private javax.swing.JSeparator separadorAgregarProveedor;
    private javax.swing.JTextField txtAgregarProveedor;
    // End of variables declaration//GEN-END:variables
}
