/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;

import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author colin
 */
public class VistaAdmin extends javax.swing.JInternalFrame {
    FondoPanel fondo = new FondoPanel();
    //Cliente mode;
    
    

    /**
     * Creates new form VistaAdmin
     */
    
    private VistaAgregarProveedor instanciaAgregarProveedor = null;
    
    public VistaAdmin() {
        this.setContentPane(fondo);
        lookAndFeel();
        initComponents();
        //setLocationRelativeTo(null);
    }
    
    /**public VistaAdmin(Cliente mode){
        initComponents();
        //setLocationRelativeTo(null);
        this.mode = mode;
        if(mode.getRol() == true){
        setVisible(true);
        }else if (mode.getRol() == false) {
            agregarAdmin.setVisible(false);
            eliminarAdmin.setVisible(false);
            actualizarAdmin.setVisible(false);
            verAdmin.setVisible(false);
        }
    }
    * */
    public void lookAndFeel(){
         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
    public synchronized VistaAgregarProveedor getInstanciaAgregarProveedor(){
        if (instanciaAgregarProveedor == null) {
            instanciaAgregarProveedor = new VistaAgregarProveedor();
            panelDeEscritorio.add(instanciaAgregarProveedor);
        }else if(instanciaAgregarProveedor.isVisible()==false)
            instanciaAgregarProveedor.setVisible(true);
        instanciaAgregarProveedor.show();
        return instanciaAgregarProveedor;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        panelDeEscritorio = new javax.swing.JDesktopPane();
        menuVistaAdmin = new javax.swing.JMenuBar();
        agregarAdmin = new javax.swing.JMenu();
        agregarProveedor = new javax.swing.JMenuItem();
        agregarCliente = new javax.swing.JMenuItem();
        agregarProducto = new javax.swing.JMenuItem();
        actualizarAdmin = new javax.swing.JMenu();
        actualizarProveedor = new javax.swing.JMenuItem();
        actualizarCliente = new javax.swing.JMenuItem();
        actualizarProducto = new javax.swing.JMenuItem();
        actualizarCompra = new javax.swing.JMenuItem();
        eliminarAdmin = new javax.swing.JMenu();
        eliminarProveedor = new javax.swing.JMenuItem();
        eliminarCliente = new javax.swing.JMenuItem();
        eliminarProducto = new javax.swing.JMenuItem();
        eliminarCompra = new javax.swing.JMenuItem();
        verAdmin = new javax.swing.JMenu();
        verProveedor = new javax.swing.JMenuItem();
        verCliente = new javax.swing.JMenuItem();
        verProducto = new javax.swing.JMenuItem();
        verCompra = new javax.swing.JMenuItem();
        menuCompra = new javax.swing.JMenu();
        itemCompra = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        javax.swing.GroupLayout panelDeEscritorioLayout = new javax.swing.GroupLayout(panelDeEscritorio);
        panelDeEscritorio.setLayout(panelDeEscritorioLayout);
        panelDeEscritorioLayout.setHorizontalGroup(
            panelDeEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        panelDeEscritorioLayout.setVerticalGroup(
            panelDeEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        agregarAdmin.setText("Agregar");

        agregarProveedor.setText("Agregar Proveedor");
        agregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProveedorActionPerformed(evt);
            }
        });
        agregarAdmin.add(agregarProveedor);

        agregarCliente.setText("Agregar Cliente");
        agregarAdmin.add(agregarCliente);

        agregarProducto.setText("Agregar Producto");
        agregarAdmin.add(agregarProducto);

        menuVistaAdmin.add(agregarAdmin);

        actualizarAdmin.setText("Actualizar");

        actualizarProveedor.setText("Actualizar Proveedor");
        actualizarAdmin.add(actualizarProveedor);

        actualizarCliente.setText("Actualizar Cliente");
        actualizarAdmin.add(actualizarCliente);

        actualizarProducto.setText("Actualizar Producto");
        actualizarAdmin.add(actualizarProducto);

        actualizarCompra.setText("Actualizar Compra");
        actualizarAdmin.add(actualizarCompra);

        menuVistaAdmin.add(actualizarAdmin);

        eliminarAdmin.setText("Eliminar");

        eliminarProveedor.setText("Eliminar Proveedor");
        eliminarAdmin.add(eliminarProveedor);

        eliminarCliente.setText("Eliminar Cliente");
        eliminarAdmin.add(eliminarCliente);

        eliminarProducto.setText("Eliminar Producto");
        eliminarAdmin.add(eliminarProducto);

        eliminarCompra.setText("Eliminar Compra");
        eliminarAdmin.add(eliminarCompra);

        menuVistaAdmin.add(eliminarAdmin);

        verAdmin.setText("Ver");

        verProveedor.setText("Ver Proveedores");
        verAdmin.add(verProveedor);

        verCliente.setText("Ver Clientes");
        verAdmin.add(verCliente);

        verProducto.setText("Ver Productos");
        verAdmin.add(verProducto);

        verCompra.setText("Ver Compras");
        verAdmin.add(verCompra);

        menuVistaAdmin.add(verAdmin);

        menuCompra.setText("Compra");

        itemCompra.setText("Hacer Compra");
        menuCompra.add(itemCompra);

        menuVistaAdmin.add(menuCompra);

        setJMenuBar(menuVistaAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDeEscritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDeEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProveedorActionPerformed
        // TODO add your handling code here:
        getInstanciaAgregarProveedor();
    }//GEN-LAST:event_agregarProveedorActionPerformed
    
    class FondoPanel extends  JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/org/ricardocolindres/recurso/login2.jpg")).getImage();
            
            g.drawImage(imagen, 1500, 750, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actualizarAdmin;
    private javax.swing.JMenuItem actualizarCliente;
    private javax.swing.JMenuItem actualizarCompra;
    private javax.swing.JMenuItem actualizarProducto;
    private javax.swing.JMenuItem actualizarProveedor;
    private javax.swing.JMenu agregarAdmin;
    private javax.swing.JMenuItem agregarCliente;
    private javax.swing.JMenuItem agregarProducto;
    private javax.swing.JMenuItem agregarProveedor;
    private javax.swing.JMenu eliminarAdmin;
    private javax.swing.JMenuItem eliminarCliente;
    private javax.swing.JMenuItem eliminarCompra;
    private javax.swing.JMenuItem eliminarProducto;
    private javax.swing.JMenuItem eliminarProveedor;
    private javax.swing.JMenuItem itemCompra;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCompra;
    private javax.swing.JMenuBar menuVistaAdmin;
    private javax.swing.JDesktopPane panelDeEscritorio;
    private javax.swing.JMenu verAdmin;
    private javax.swing.JMenuItem verCliente;
    private javax.swing.JMenuItem verCompra;
    private javax.swing.JMenuItem verProducto;
    private javax.swing.JMenuItem verProveedor;
    // End of variables declaration//GEN-END:variables

    
}
