/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;
import org.ricardocolindres.modelo.Doctor;
import org.ricardocolindres.controlador.ControlDoctor;

/**
 * Clase que contiene la Vista de Ver Doctores
 * @author Ricardo Adrian Colindres Franco
 * @version  1.0
 * @see Doctor
 * @see ControlDoctor
 */
public class VistaVerDoctores extends javax.swing.JInternalFrame {
    /**
     * instancias nuevas
     */
    
    public ControlDoctor controlador = ControlDoctor.getInstancia();

    /**
     * Creates new form VistaVerDoctores
     */
    public VistaVerDoctores() {
        initComponents();
    }
    
    public  void mostrarDatosDoctores(){
        /**
         * obtener los datos
         */
        String [] encabezados = {"Id Doctor", "Nombre Doctor", "Apellido Doctor", "Numero de Telefono", "Especialidad", "Email", "Direccion", "Colegiado"};
        int cantidadDeDoctores = controlador.cantidadDeDoctores();
        
        DefaultTableModel cabecera = new DefaultTableModel(encabezados, cantidadDeDoctores);
        tablaDeDoctores.setModel(cabecera);
        TableModel listaDeDoctores = tablaDeDoctores.getModel();
        
        for(int i=0; i<cantidadDeDoctores; i++){
            Doctor doctor = new Doctor();
            doctor = controlador.listaDeDoctores().get(i);
            listaDeDoctores.setValueAt(doctor.getId(), i, 0);
            listaDeDoctores.setValueAt(doctor.getNombre(), i, 1);
            listaDeDoctores.setValueAt(doctor.getApellido(), i, 2);
            listaDeDoctores.setValueAt(doctor.getNumero(), i, 3);
            listaDeDoctores.setValueAt(doctor.getEspecialidad(), i, 4);
            listaDeDoctores.setValueAt(doctor.getEmail(), i, 5);
            listaDeDoctores.setValueAt(doctor.getDireccion(), i, 6);
            listaDeDoctores.setValueAt(doctor.getColegiado(), i, 7);

            
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelTablaDeDoctores = new javax.swing.JScrollPane();
        tablaDeDoctores = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        tablaDeDoctores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Doctor", "Nombre Doctor", "Apellido Doctor", "Numero de Telefono", "Especialidad", "Email", "Direccion", "Colegiado"
            }
        ));
        scrollPanelTablaDeDoctores.setViewportView(tablaDeDoctores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollPanelTablaDeDoctores, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPanelTablaDeDoctores, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPanelTablaDeDoctores;
    private javax.swing.JTable tablaDeDoctores;
    // End of variables declaration//GEN-END:variables
}
