/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;
import org.ricardocolindres.modelo.Mascota;
import org.ricardocolindres.controlador.ControlMascota;

/**
 * Clase que contiene la Vista de Ver Mascotas
 * @author Ricardo Adrian Colindres Franco
 * @version  1.0
 * @see Mascota
 * @see ControlMascota
 */
public class VistaVerMascotas extends javax.swing.JInternalFrame {
    /**
     * instancias nuevas
     */
    
    public ControlMascota controlador = ControlMascota.getInstancia();

    /**
     * Creates new form VistaVerMascotas
     */
    public VistaVerMascotas() {
        initComponents();
    }
    
    public void mostrarDatosMascotas(){
        /**
         * obtener los datos
         */
        String [] encabezados = {"Id Mascota", "Nombre Mascota", "Duenio Mascota", "Especie Mascota", "Raza Mascota"};
        int cantidadDeMascotas = controlador.cantidadDeMascotas();  
        
        DefaultTableModel cabecera = new DefaultTableModel(encabezados, cantidadDeMascotas);
        tablaDeMascotas.setModel(cabecera);
        TableModel listaDeMascotas = tablaDeMascotas.getModel();
        
        for(int i=0; i<cantidadDeMascotas;i++){
            Mascota mascota = new Mascota();
            mascota = controlador.listaDeMascotas().get(i);
            listaDeMascotas.setValueAt(mascota.getId(), i, 0);
            listaDeMascotas.setValueAt(mascota.getNombre(), i, 1);
            listaDeMascotas.setValueAt(mascota.getDuenio(), i, 2);
            listaDeMascotas.setValueAt(mascota.getEspecie(), i, 3);
            listaDeMascotas.setValueAt(mascota.getRaza(), i, 4);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelVistaVerMascotas = new javax.swing.JScrollPane();
        tablaDeMascotas = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        tablaDeMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Mascota", "Nombre Mascota", "Duenio Mascota", "Especie Mascota", "Raza Mascota"
            }
        ));
        scrollPanelVistaVerMascotas.setViewportView(tablaDeMascotas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelVistaVerMascotas, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelVistaVerMascotas, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPanelVistaVerMascotas;
    private javax.swing.JTable tablaDeMascotas;
    // End of variables declaration//GEN-END:variables
}
