/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import org.ricardocolindres.controlador.ControlCita;
import org.ricardocolindres.modelo.Cita;
/**
 * Clase que contiene la Vista de Actualizar Cita
 * @author Ricardo Adrian Colindres Franco
 * @version  1.0
 * @see Cita
 * @see ControlCita
 */
public class VistaActualizarCita extends javax.swing.JInternalFrame {
    /**
     * instancias nuevas
     */
    Cita citaAntiguo = new Cita();
    Cita citaActualizado = new Cita();
    ControlCita controlador = ControlCita.getInstancia();

    /**
     * Creates new form VistaActualizarCita
     */
    public VistaActualizarCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActualizarCita = new javax.swing.JPanel();
        lblIdCitaActualizar = new javax.swing.JLabel();
        lblDiaCitaActualizar = new javax.swing.JLabel();
        lblMesCitaActualizar = new javax.swing.JLabel();
        lblAnioCitaActualizar = new javax.swing.JLabel();
        lblClienteCitaActualizar = new javax.swing.JLabel();
        lblHoraCitaActualizar = new javax.swing.JLabel();
        txtIdCitaActualizar = new javax.swing.JTextField();
        txtDiaCitaActualizar = new javax.swing.JTextField();
        txtMesCitaActualizar = new javax.swing.JTextField();
        txtAnioCitaActualizar = new javax.swing.JTextField();
        txtClienteCitaActualizar = new javax.swing.JTextField();
        txtHoraCitaActualizar = new javax.swing.JTextField();
        separadorActualizarCita = new javax.swing.JSeparator();
        botonActualizarCita = new javax.swing.JButton();
        separadorBuscarIdCitaActualizar = new javax.swing.JSeparator();
        lblIdCitaBuscarActualizar = new javax.swing.JLabel();
        txtIdCitaBuscarActualizar = new javax.swing.JTextField();
        botonBuscarIdActualizar = new javax.swing.JButton();

        lblIdCitaActualizar.setText("Id Cita");

        lblDiaCitaActualizar.setText("Dia Cita");

        lblMesCitaActualizar.setText("Mes Cita");

        lblAnioCitaActualizar.setText("Anio Cita");

        lblClienteCitaActualizar.setText("Cliente Cita");

        lblHoraCitaActualizar.setText("Hora Cita");

        botonActualizarCita.setText("Actualizar Datos");
        botonActualizarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarCitaActionPerformed(evt);
            }
        });

        lblIdCitaBuscarActualizar.setText("ID de Cita a buscar");

        botonBuscarIdActualizar.setText("Buscar");
        botonBuscarIdActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarIdActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActualizarCitaLayout = new javax.swing.GroupLayout(panelActualizarCita);
        panelActualizarCita.setLayout(panelActualizarCitaLayout);
        panelActualizarCitaLayout.setHorizontalGroup(
            panelActualizarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActualizarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelActualizarCitaLayout.createSequentialGroup()
                        .addGroup(panelActualizarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separadorActualizarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(separadorBuscarIdCitaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelActualizarCitaLayout.createSequentialGroup()
                        .addGroup(panelActualizarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdCitaActualizar)
                            .addComponent(lblDiaCitaActualizar)
                            .addComponent(lblMesCitaActualizar)
                            .addComponent(lblAnioCitaActualizar)
                            .addComponent(lblClienteCitaActualizar)
                            .addComponent(lblHoraCitaActualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelActualizarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIdCitaBuscarActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtClienteCitaActualizar)
                            .addComponent(txtAnioCitaActualizar)
                            .addComponent(txtMesCitaActualizar)
                            .addComponent(txtDiaCitaActualizar)
                            .addComponent(txtIdCitaActualizar))
                        .addGap(31, 31, 31))
                    .addGroup(panelActualizarCitaLayout.createSequentialGroup()
                        .addComponent(lblIdCitaBuscarActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHoraCitaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(panelActualizarCitaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(botonBuscarIdActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarCitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonActualizarCita)
                .addGap(32, 32, 32))
        );
        panelActualizarCitaLayout.setVerticalGroup(
            panelActualizarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActualizarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCitaActualizar)
                    .addComponent(txtIdCitaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActualizarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaCitaActualizar)
                    .addComponent(txtDiaCitaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActualizarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMesCitaActualizar)
                    .addComponent(txtMesCitaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnioCitaActualizar)
                    .addComponent(txtAnioCitaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteCitaActualizar)
                    .addComponent(txtClienteCitaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelActualizarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraCitaActualizar)
                    .addComponent(txtIdCitaBuscarActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separadorActualizarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonActualizarCita)
                .addGap(12, 12, 12)
                .addComponent(separadorBuscarIdCitaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCitaBuscarActualizar)
                    .addComponent(txtHoraCitaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonBuscarIdActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelActualizarCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelActualizarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarIdActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarIdActualizarActionPerformed
        /**
         * obtener todos los datos
         */
// TODO add your handling code here:
        citaAntiguo = controlador.buscarCita(Integer.parseInt(txtIdCitaBuscarActualizar.getText()));
        txtIdCitaActualizar.setText(String.valueOf(citaAntiguo.getId()));
        txtDiaCitaActualizar.setText(String.valueOf(citaAntiguo.getDia()));
        txtMesCitaActualizar.setText(citaAntiguo.getMes());
        txtAnioCitaActualizar.setText(String.valueOf(citaAntiguo.getAnio()));
        txtClienteCitaActualizar.setText(citaAntiguo.getCliente());
        txtHoraCitaActualizar.setText(String.valueOf(citaAntiguo.getHora()));
    }//GEN-LAST:event_botonBuscarIdActualizarActionPerformed

    private void botonActualizarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarCitaActionPerformed
        
        // TODO add your handling code here:
        citaActualizado.setId(Integer.parseInt(txtIdCitaActualizar.getText()));
        citaActualizado.setDia(Integer.parseInt(txtDiaCitaActualizar.getText()));
        citaActualizado.setMes(txtMesCitaActualizar.getText());
        citaActualizado.setAnio(Integer.parseInt(txtAnioCitaActualizar.getText()));
        citaActualizado.setCliente(txtClienteCitaActualizar.getText());
        citaActualizado.setHora(txtHoraCitaActualizar.getText());
        controlador.actualizarCita(citaAntiguo, citaActualizado);
        setVisible(false);
    }//GEN-LAST:event_botonActualizarCitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarCita;
    private javax.swing.JButton botonBuscarIdActualizar;
    private javax.swing.JLabel lblAnioCitaActualizar;
    private javax.swing.JLabel lblClienteCitaActualizar;
    private javax.swing.JLabel lblDiaCitaActualizar;
    private javax.swing.JLabel lblHoraCitaActualizar;
    private javax.swing.JLabel lblIdCitaActualizar;
    private javax.swing.JLabel lblIdCitaBuscarActualizar;
    private javax.swing.JLabel lblMesCitaActualizar;
    private javax.swing.JPanel panelActualizarCita;
    private javax.swing.JSeparator separadorActualizarCita;
    private javax.swing.JSeparator separadorBuscarIdCitaActualizar;
    private javax.swing.JTextField txtAnioCitaActualizar;
    private javax.swing.JTextField txtClienteCitaActualizar;
    private javax.swing.JTextField txtDiaCitaActualizar;
    private javax.swing.JTextField txtHoraCitaActualizar;
    private javax.swing.JTextField txtIdCitaActualizar;
    private javax.swing.JTextField txtIdCitaBuscarActualizar;
    private javax.swing.JTextField txtMesCitaActualizar;
    // End of variables declaration//GEN-END:variables
}
