/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import org.ricardocolindres.controlador.ControlCita;
import org.ricardocolindres.modelo.Cita;

/**
 * Clase que contiene la Vista de Eliminar Cita
 * @author Ricardo Adrian Colindres Franco
 * @version  1.0
 * @see Cita
 * @see ControlCita
 */
public class VistaEliminarCita extends javax.swing.JInternalFrame {
    /**
     * instancias nuevas
     */
    Cita cita = new Cita();
    public ControlCita controlador = ControlCita.getInstancia();
    
    
    
    /**
     * Creates new form VistaEliminarCita
     */
    public VistaEliminarCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCitaEliminar = new javax.swing.JPanel();
        lblIdCitaEliminar = new javax.swing.JLabel();
        txtIdCitaEliminar = new javax.swing.JTextField();
        botonEliminarCita = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        lblIdCitaEliminar.setText("Id Cita a Eliminar");

        botonEliminarCita.setText("Eliminar");
        botonEliminarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCitaEliminarLayout = new javax.swing.GroupLayout(panelCitaEliminar);
        panelCitaEliminar.setLayout(panelCitaEliminarLayout);
        panelCitaEliminarLayout.setHorizontalGroup(
            panelCitaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCitaEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdCitaEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(panelCitaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminarCita)
                    .addComponent(txtIdCitaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        panelCitaEliminarLayout.setVerticalGroup(
            panelCitaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCitaEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCitaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCitaEliminar)
                    .addComponent(txtIdCitaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonEliminarCita)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCitaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelCitaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarCitaActionPerformed
        /**
         * obtener los datos
         */
        // TODO add your handling code here:
        controlador.eliminarCita(cita);
        txtIdCitaEliminar.setText(String.valueOf(cita.getId()));
    }//GEN-LAST:event_botonEliminarCitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarCita;
    private javax.swing.JLabel lblIdCitaEliminar;
    private javax.swing.JPanel panelCitaEliminar;
    private javax.swing.JTextField txtIdCitaEliminar;
    // End of variables declaration//GEN-END:variables
}
