/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import org.ricardocolindres.controlador.ControlCliente;
import org.ricardocolindres.modelo.Cliente;

/**
 * Clase que contiene la Vista de Agregar Cliente
 * @author Ricardo Adrian Colindres Franco
 * @version  1.0
 * @see Cliente
 * @see ControlCliente
 */
public class VistaAgregarCliente extends javax.swing.JInternalFrame {
    /**
     * instancia nueva
     */
    ControlCliente controlador = ControlCliente.getInstancia();

    /**
     * Creates new form VistaAgregarCliente
     */
    public VistaAgregarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGuardarCliente = new javax.swing.JPanel();
        lblIdCliente = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblApellidoCliente = new javax.swing.JLabel();
        lblNumTelefonoCliente = new javax.swing.JLabel();
        lblEmailCliente = new javax.swing.JLabel();
        lblDuenioCliente = new javax.swing.JLabel();
        txtIdClienteGuardar = new javax.swing.JTextField();
        txtNombreClienteGuardar = new javax.swing.JTextField();
        txtApellidoClienteGuardar = new javax.swing.JTextField();
        txtNumeroClienteGuardar = new javax.swing.JTextField();
        txtEmailClienteGuardar = new javax.swing.JTextField();
        txtDuenioClienteGuardar = new javax.swing.JTextField();
        separadorClienteGuardar = new javax.swing.JSeparator();
        botonGuardarCliente = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        lblIdCliente.setText("Id Cliente");

        lblNombreCliente.setText("Nombre Cliente");

        lblApellidoCliente.setText("Apellido Cliente");

        lblNumTelefonoCliente.setText("Numero Telefono Cliente");

        lblEmailCliente.setText("Email Cliente");

        lblDuenioCliente.setText("Cliente duenio de ");

        botonGuardarCliente.setText("Guardar Cliente");
        botonGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGuardarClienteLayout = new javax.swing.GroupLayout(panelGuardarCliente);
        panelGuardarCliente.setLayout(panelGuardarClienteLayout);
        panelGuardarClienteLayout.setHorizontalGroup(
            panelGuardarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGuardarClienteLayout.createSequentialGroup()
                .addGroup(panelGuardarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdCliente)
                    .addComponent(lblNombreCliente)
                    .addComponent(lblApellidoCliente)
                    .addComponent(lblNumTelefonoCliente)
                    .addComponent(lblEmailCliente)
                    .addComponent(lblDuenioCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGuardarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDuenioClienteGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailClienteGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroClienteGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoClienteGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreClienteGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdClienteGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(panelGuardarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGuardarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonGuardarCliente)
                    .addComponent(separadorClienteGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        panelGuardarClienteLayout.setVerticalGroup(
            panelGuardarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarClienteLayout.createSequentialGroup()
                .addGroup(panelGuardarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCliente)
                    .addComponent(txtIdClienteGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelGuardarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCliente)
                    .addComponent(txtNombreClienteGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGuardarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellidoCliente)
                    .addComponent(txtApellidoClienteGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGuardarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumTelefonoCliente)
                    .addComponent(txtNumeroClienteGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGuardarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmailCliente)
                    .addComponent(txtEmailClienteGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGuardarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDuenioCliente)
                    .addComponent(txtDuenioClienteGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separadorClienteGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGuardarCliente)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(panelGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGuardarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarClienteActionPerformed
             /**
         * obtener todos los datos
         */
    // TODO add your handling code here:
        Cliente cliente = new Cliente();
        cliente.setIdCl(Integer.parseInt(txtIdClienteGuardar.getText()));
        cliente.setNombreCli(txtNombreClienteGuardar.getText());
        cliente.setApellidoCli(txtApellidoClienteGuardar.getText());
        cliente.setNumCliente(Integer.parseInt(txtNumeroClienteGuardar.getText()));
        cliente.setEmailClie(txtEmailClienteGuardar.getText());
        cliente.setDuenioClie(txtDuenioClienteGuardar.getText());
        
        controlador.agregarClientes(cliente);
        
        txtIdClienteGuardar.setText(" ");
        txtNombreClienteGuardar.setText(" ");
        txtApellidoClienteGuardar.setText(" ");
        txtNumeroClienteGuardar.setText(" ");
        txtEmailClienteGuardar.setText(" ");
        txtDuenioClienteGuardar.setText(" ");
        
        setVisible(false);
    }//GEN-LAST:event_botonGuardarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarCliente;
    private javax.swing.JLabel lblApellidoCliente;
    private javax.swing.JLabel lblDuenioCliente;
    private javax.swing.JLabel lblEmailCliente;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNumTelefonoCliente;
    private javax.swing.JPanel panelGuardarCliente;
    private javax.swing.JSeparator separadorClienteGuardar;
    private javax.swing.JTextField txtApellidoClienteGuardar;
    private javax.swing.JTextField txtDuenioClienteGuardar;
    private javax.swing.JTextField txtEmailClienteGuardar;
    private javax.swing.JTextField txtIdClienteGuardar;
    private javax.swing.JTextField txtNombreClienteGuardar;
    private javax.swing.JTextField txtNumeroClienteGuardar;
    // End of variables declaration//GEN-END:variables
}
