/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import org.ricardocolindres.controlador.ControlMascota;
import org.ricardocolindres.modelo.Mascota;

/**
 * Clase que contiene la Vista de Eliminar Doctor
 * @author Ricardo Adrian Colindres Franco
 * @version  1.0
 * @see Mascota
 * @see ControlMascota
 */
public class VistaEliminarMascota extends javax.swing.JInternalFrame {
    /**
     * instancias nuevas
     */
    Mascota mascota = new Mascota();
    public ControlMascota controlador = ControlMascota.getInstancia();
    
    

    /**
     * Creates new form VistaEliminarMascota
     */
    public VistaEliminarMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEliminarMascota = new javax.swing.JPanel();
        lblIdMascotaEliminar = new javax.swing.JLabel();
        txtIdMascotaEliminar = new javax.swing.JTextField();
        botonEliminarMascota = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        lblIdMascotaEliminar.setText("Id de la Mascota a Eliminar");

        botonEliminarMascota.setText("Eliminar");
        botonEliminarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarMascotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEliminarMascotaLayout = new javax.swing.GroupLayout(panelEliminarMascota);
        panelEliminarMascota.setLayout(panelEliminarMascotaLayout);
        panelEliminarMascotaLayout.setHorizontalGroup(
            panelEliminarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarMascotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdMascotaEliminar)
                .addGap(51, 51, 51)
                .addGroup(panelEliminarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminarMascota)
                    .addComponent(txtIdMascotaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelEliminarMascotaLayout.setVerticalGroup(
            panelEliminarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarMascotaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelEliminarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdMascotaEliminar)
                    .addComponent(txtIdMascotaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(botonEliminarMascota)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelEliminarMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEliminarMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarMascotaActionPerformed
        /**
         * obtener los datos
         */
// TODO add your handling code here:
        controlador.eliminarMascota(mascota);
        txtIdMascotaEliminar.setText(String.valueOf(mascota.getId()));
    }//GEN-LAST:event_botonEliminarMascotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarMascota;
    private javax.swing.JLabel lblIdMascotaEliminar;
    private javax.swing.JPanel panelEliminarMascota;
    private javax.swing.JTextField txtIdMascotaEliminar;
    // End of variables declaration//GEN-END:variables
}
