/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import org.ricardocolindres.controlador.ControlCliente;
import org.ricardocolindres.modelo.Cliente;

/**
 * Clase que contiene la Vista de Eliminar Cliente
 * @author Ricardo Adrian Colindres Franco
 * @version  1.0
 * @see Cliente
 * @see ControlCliente
 */
public class VistaEliminarCliente extends javax.swing.JInternalFrame {
    /**
     * instancias nuevas
     */
    Cliente cliente = new Cliente();
    public ControlCliente controlador = ControlCliente.getInstancia();
    
    
    /**
     * Creates new form VistaEliminarCliente
     */
    public VistaEliminarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelClienteEliminar = new javax.swing.JPanel();
        botonEliminarCliente = new javax.swing.JButton();
        lblIdClienteEliminar = new javax.swing.JLabel();
        txtIdClienteEliminar = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        botonEliminarCliente.setText("Eliminar");
        botonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClienteEliminarLayout = new javax.swing.GroupLayout(panelClienteEliminar);
        panelClienteEliminar.setLayout(panelClienteEliminarLayout);
        panelClienteEliminarLayout.setHorizontalGroup(
            panelClienteEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteEliminarLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(botonEliminarCliente)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelClienteEliminarLayout.setVerticalGroup(
            panelClienteEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteEliminarLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(botonEliminarCliente)
                .addContainerGap())
        );

        lblIdClienteEliminar.setText("Id del Cliente a Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIdClienteEliminar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(txtIdClienteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelClienteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(txtIdClienteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelClienteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblIdClienteEliminar)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarClienteActionPerformed
        /**
         * obtener los datos
         */
        controlador.eliminarCliente(cliente);
        txtIdClienteEliminar.setText(String.valueOf(cliente.getIdCl()));
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarCliente;
    private javax.swing.JLabel lblIdClienteEliminar;
    private javax.swing.JPanel panelClienteEliminar;
    private javax.swing.JTextField txtIdClienteEliminar;
    // End of variables declaration//GEN-END:variables
}
