/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import org.ricardocolindres.controlador.ControlCliente;
import org.ricardocolindres.modelo.Cliente;

/**
 * Clase que contiene la Vista de Actualizar Cliente
 * @author Ricardo Adrian Colindres Franco
 * @version  1.0
 * @see Cliente
 * @see ControlCliente
 */
public class VistaActualizarCliente extends javax.swing.JInternalFrame {
    /**
     * instancias nuevas
     */
    
    Cliente clienteAntiguo = new Cliente();
    Cliente clienteActualizado = new Cliente();
    ControlCliente controlador = ControlCliente.getInstancia();
    /**
     * Creates new form VistaActualizarCliente
     */
    public VistaActualizarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActualizarCliente = new javax.swing.JPanel();
        txtIdClienteActualizar = new javax.swing.JTextField();
        txtNombreClienteActualizar = new javax.swing.JTextField();
        txtApellidoClienteActualizar = new javax.swing.JTextField();
        txtNumeroClienteActualizar = new javax.swing.JTextField();
        txtEmailClienteActualizar = new javax.swing.JTextField();
        txtDuenioClienteActualizar = new javax.swing.JTextField();
        lblIdClienteActualizar = new javax.swing.JLabel();
        lblNombreClienteActualizar = new javax.swing.JLabel();
        lblApellidoClienteActualizar = new javax.swing.JLabel();
        lblNumeroTelefonoCliente = new javax.swing.JLabel();
        lblEmailClienteActualizar = new javax.swing.JLabel();
        lblDuenioClienteActualizar = new javax.swing.JLabel();
        separadorActualizarCliente = new javax.swing.JSeparator();
        botonActualizarCliente = new javax.swing.JButton();
        separadorBuscarIdCliente = new javax.swing.JSeparator();
        lblBuscarIdCliente = new javax.swing.JLabel();
        txtIdClienteBuscarActualizar = new javax.swing.JTextField();
        botonBuscarIdCliente = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        lblIdClienteActualizar.setText("Id Cliente");

        lblNombreClienteActualizar.setText("Nombre Cliente");

        lblApellidoClienteActualizar.setText("Apellido Cliente");

        lblNumeroTelefonoCliente.setText("Numero Telefono Cliente");

        lblEmailClienteActualizar.setText("Email Cliente");

        lblDuenioClienteActualizar.setText("Duenio Cliente");

        botonActualizarCliente.setText("Actualizar Datos");
        botonActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarClienteActionPerformed(evt);
            }
        });

        lblBuscarIdCliente.setText("ID del Cliente a buscar");

        botonBuscarIdCliente.setText("Buscar");
        botonBuscarIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarIdClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActualizarClienteLayout = new javax.swing.GroupLayout(panelActualizarCliente);
        panelActualizarCliente.setLayout(panelActualizarClienteLayout);
        panelActualizarClienteLayout.setHorizontalGroup(
            panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonActualizarCliente)
                .addGap(21, 21, 21))
            .addGroup(panelActualizarClienteLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblBuscarIdCliente)
                .addGap(18, 18, 18)
                .addComponent(txtIdClienteBuscarActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelActualizarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarClienteLayout.createSequentialGroup()
                        .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarClienteLayout.createSequentialGroup()
                                .addComponent(lblNombreClienteActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombreClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarClienteLayout.createSequentialGroup()
                                .addComponent(lblApellidoClienteActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtApellidoClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarClienteLayout.createSequentialGroup()
                                .addComponent(lblIdClienteActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarClienteLayout.createSequentialGroup()
                                .addComponent(lblDuenioClienteActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDuenioClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarClienteLayout.createSequentialGroup()
                                .addComponent(lblNumeroTelefonoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNumeroClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarClienteLayout.createSequentialGroup()
                                .addComponent(lblEmailClienteActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmailClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(panelActualizarClienteLayout.createSequentialGroup()
                        .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separadorActualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(separadorBuscarIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBuscarIdCliente))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelActualizarClienteLayout.setVerticalGroup(
            panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdClienteActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreClienteActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidoClienteActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroTelefonoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailClienteActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuenioClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuenioClienteActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separadorActualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonActualizarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorBuscarIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarIdCliente)
                    .addComponent(txtIdClienteBuscarActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonBuscarIdCliente)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelActualizarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarIdClienteActionPerformed
       /**
         * obtener todos los datos
         */
        // TODO add your handling code here:
        clienteAntiguo = controlador.buscarCliente(Integer.parseInt(txtIdClienteBuscarActualizar.getText()));
        txtIdClienteActualizar.setText(String.valueOf(clienteAntiguo.getIdCl()));
        txtNombreClienteActualizar.setText(clienteAntiguo.getNombreCli());
        txtApellidoClienteActualizar.setText(clienteAntiguo.getApellidoCli());
        txtNumeroClienteActualizar.setText(String.valueOf(clienteAntiguo.getNumCliente()));
        txtEmailClienteActualizar.setText(clienteAntiguo.getEmailClie());
        txtDuenioClienteActualizar.setText(clienteAntiguo.getDuenioClie());
    }//GEN-LAST:event_botonBuscarIdClienteActionPerformed

    private void botonActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarClienteActionPerformed
        // TODO add your handling code here:
        clienteActualizado.setIdCl(Integer.parseInt(txtIdClienteActualizar.getText()));
        clienteActualizado.setNombreCli(txtNombreClienteActualizar.getText());
        clienteActualizado.setApellidoCli(txtApellidoClienteActualizar.getText());
        clienteActualizado.setNumCliente(Integer.parseInt(txtNumeroClienteActualizar.getText()));
        clienteActualizado.setEmailClie(txtEmailClienteActualizar.getText());
        controlador.actualizarCliente(clienteAntiguo, clienteActualizado);
        setVisible(false);
    }//GEN-LAST:event_botonActualizarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarCliente;
    private javax.swing.JButton botonBuscarIdCliente;
    private javax.swing.JLabel lblApellidoClienteActualizar;
    private javax.swing.JLabel lblBuscarIdCliente;
    private javax.swing.JLabel lblDuenioClienteActualizar;
    private javax.swing.JLabel lblEmailClienteActualizar;
    private javax.swing.JLabel lblIdClienteActualizar;
    private javax.swing.JLabel lblNombreClienteActualizar;
    private javax.swing.JLabel lblNumeroTelefonoCliente;
    private javax.swing.JPanel panelActualizarCliente;
    private javax.swing.JSeparator separadorActualizarCliente;
    private javax.swing.JSeparator separadorBuscarIdCliente;
    private javax.swing.JTextField txtApellidoClienteActualizar;
    private javax.swing.JTextField txtDuenioClienteActualizar;
    private javax.swing.JTextField txtEmailClienteActualizar;
    private javax.swing.JTextField txtIdClienteActualizar;
    private javax.swing.JTextField txtIdClienteBuscarActualizar;
    private javax.swing.JTextField txtNombreClienteActualizar;
    private javax.swing.JTextField txtNumeroClienteActualizar;
    // End of variables declaration//GEN-END:variables
}
