/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import org.ricardocolindres.modelo.Mascota;
import org.ricardocolindres.controlador.ControlMascota;

/**
 * Clase que contiene la Vista de Agregar Mascota
 * @author Ricardo Adrian Colindres Franco
 * @version  1.0
 * @see Mascota
 * @see ControlMascota
 */
public class VistaAgregarMascota extends javax.swing.JInternalFrame {
    /**
     * instancia nueva
     */
    ControlMascota controlador = ControlMascota.getInstancia();

    /**
     * Creates new form VistaAgregarMascota
     */
    public VistaAgregarMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGuardarMascota = new javax.swing.JPanel();
        lblIdMascotaAgregar = new javax.swing.JLabel();
        lblNombreMascotaAgregar = new javax.swing.JLabel();
        lblDuenioMascotaAgregar = new javax.swing.JLabel();
        lblEspecieMascotaAgregar = new javax.swing.JLabel();
        lblRazaMascotaAgregar = new javax.swing.JLabel();
        txtIdMascotaAgregar = new javax.swing.JTextField();
        txtNombreMascotaAgregar = new javax.swing.JTextField();
        txtDuenioMascotaAgregar = new javax.swing.JTextField();
        txtEspecieMascotaAgregar = new javax.swing.JTextField();
        txtRazaMascotaAgregar = new javax.swing.JTextField();
        separadorGuardarMascota = new javax.swing.JSeparator();
        botonGuardarMascota = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        lblIdMascotaAgregar.setText("Id Mascota");

        lblNombreMascotaAgregar.setText("Nombre Mascota");

        lblDuenioMascotaAgregar.setText("Duenio Mascota");

        lblEspecieMascotaAgregar.setText("Especie Mascota");

        lblRazaMascotaAgregar.setText("Raza Mascota");

        botonGuardarMascota.setText("Guardar Mascota");
        botonGuardarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarMascotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGuardarMascotaLayout = new javax.swing.GroupLayout(panelGuardarMascota);
        panelGuardarMascota.setLayout(panelGuardarMascotaLayout);
        panelGuardarMascotaLayout.setHorizontalGroup(
            panelGuardarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarMascotaLayout.createSequentialGroup()
                .addGroup(panelGuardarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadorGuardarMascota)
                    .addGroup(panelGuardarMascotaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelGuardarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGuardarMascotaLayout.createSequentialGroup()
                                .addGroup(panelGuardarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdMascotaAgregar)
                                    .addComponent(lblNombreMascotaAgregar)
                                    .addComponent(lblDuenioMascotaAgregar)
                                    .addComponent(lblEspecieMascotaAgregar)
                                    .addComponent(lblRazaMascotaAgregar))
                                .addGroup(panelGuardarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelGuardarMascotaLayout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addGroup(panelGuardarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreMascotaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdMascotaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDuenioMascotaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGuardarMascotaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelGuardarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRazaMascotaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEspecieMascotaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGuardarMascotaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonGuardarMascota)))))
                .addContainerGap())
        );
        panelGuardarMascotaLayout.setVerticalGroup(
            panelGuardarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarMascotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGuardarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGuardarMascotaLayout.createSequentialGroup()
                        .addGroup(panelGuardarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdMascotaAgregar)
                            .addComponent(txtIdMascotaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panelGuardarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreMascotaAgregar)
                            .addComponent(txtNombreMascotaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelGuardarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDuenioMascotaAgregar)
                            .addComponent(txtDuenioMascotaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblEspecieMascotaAgregar))
                    .addComponent(txtEspecieMascotaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGuardarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazaMascotaAgregar)
                    .addComponent(txtRazaMascotaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separadorGuardarMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGuardarMascota)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGuardarMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGuardarMascota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarMascotaActionPerformed
        /**
         * obtener todos los datos
         */
        
// TODO add your handling code here:
        Mascota mascota = new Mascota();
        mascota.setId(Integer.parseInt(txtIdMascotaAgregar.getText()));
        mascota.setNombre(txtNombreMascotaAgregar.getText());
        mascota.setDuenio(txtDuenioMascotaAgregar.getText());
        mascota.setEspecie(txtEspecieMascotaAgregar.getText());
        mascota.setRaza(txtRazaMascotaAgregar.getText());

        
        controlador.agregarMascotas(mascota);
        
        txtIdMascotaAgregar.setText("");
        txtNombreMascotaAgregar.setText("");
        txtDuenioMascotaAgregar.setText("");
        txtEspecieMascotaAgregar.setText("");
        txtRazaMascotaAgregar.setText("");
        
        setVisible(false);
    }//GEN-LAST:event_botonGuardarMascotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarMascota;
    private javax.swing.JLabel lblDuenioMascotaAgregar;
    private javax.swing.JLabel lblEspecieMascotaAgregar;
    private javax.swing.JLabel lblIdMascotaAgregar;
    private javax.swing.JLabel lblNombreMascotaAgregar;
    private javax.swing.JLabel lblRazaMascotaAgregar;
    private javax.swing.JPanel panelGuardarMascota;
    private javax.swing.JSeparator separadorGuardarMascota;
    private javax.swing.JTextField txtDuenioMascotaAgregar;
    private javax.swing.JTextField txtEspecieMascotaAgregar;
    private javax.swing.JTextField txtIdMascotaAgregar;
    private javax.swing.JTextField txtNombreMascotaAgregar;
    private javax.swing.JTextField txtRazaMascotaAgregar;
    // End of variables declaration//GEN-END:variables
}
