/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;
import org.ricardocolindres.controlador.ControlCita;
import org.ricardocolindres.modelo.Cita;


/**
 * Clase que contiene la Vista de Ver Citas
 * @author Ricardo Adrian Colindres Franco
 * @version  1.0
 * @see Cita
 * @see ControlCita
 */
public class VistaVerCitas extends javax.swing.JInternalFrame {
    /**
     * instancias nuevas
     */
    public ControlCita controlador = ControlCita.getInstancia();

    /**
     * Creates new form VistaVerCitas
     */
    public VistaVerCitas() {
        initComponents();
    }
    
    public void mostrarDatosCita(){
        /**
         * obtener los datos
         */
        String [] encabezados ={"Id Cita", "Dia Cita", "Mes Cita", "Anio Cita", "Cliente Cita", "Hora Cita"};   
        int cantidadDeCitas = controlador.cantidadDeCitas();
        
        DefaultTableModel cabecera = new DefaultTableModel(encabezados, cantidadDeCitas);
        tablaVerCitas.setModel(cabecera);
        TableModel listaDeCitas = tablaVerCitas.getModel();
        
        for(int i=0; i<cantidadDeCitas;i++){
            Cita cita = new Cita();
            cita = controlador.listaCitas().get(i);
            listaDeCitas.setValueAt(cita.getId(), i, 0);
            listaDeCitas.setValueAt(cita.getDia(), i, 1);
            listaDeCitas.setValueAt(cita.getMes(), i, 2);
            listaDeCitas.setValueAt(cita.getAnio(), i, 3);
            listaDeCitas.setValueAt(cita.getCliente(), i, 4);
            listaDeCitas.setValueAt(cita.getHora(), i, 5);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelVerCitas = new javax.swing.JScrollPane();
        tablaVerCitas = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        tablaVerCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Cita", "Dia Cita", "Mes Cita", "Anio Cita", "Cliente Cita", "Hora Cita"
            }
        ));
        scrollPanelVerCitas.setViewportView(tablaVerCitas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelVerCitas, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelVerCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPanelVerCitas;
    private javax.swing.JTable tablaVerCitas;
    // End of variables declaration//GEN-END:variables
}
