/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import org.ricardocolindres.controlador.ControlDoctor;

import org.ricardocolindres.modelo.Doctor;

/**
 *Clase que contiene la Vista de Agregar Doctor
 * @author Ricardo Adrian Colindres Franco
 * @version  1.0
 * @see Doctor
 * @see ControlDoctor
 */
public class VistaAgregarDoctor extends javax.swing.JInternalFrame {
    /**
     * instancia nueva
     */
    
    ControlDoctor controlador = ControlDoctor.getInstancia();

    /**
     * Creates new form VistaAgregarDoctor
     */
    public VistaAgregarDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        panelGuardarDoctor = new javax.swing.JPanel();
        lblIdDoctor = new javax.swing.JLabel();
        lblNombreDoctor = new javax.swing.JLabel();
        lblApellidoDoctor = new javax.swing.JLabel();
        lblNumeroTelefono = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblColegiado = new javax.swing.JLabel();
        txtIdDoctorGuardar = new javax.swing.JTextField();
        txtNombreDoctorGuardar = new javax.swing.JTextField();
        txtApellidoDoctorGuardar = new javax.swing.JTextField();
        txtNumeroTelefonoGuardar = new javax.swing.JTextField();
        txtEspecialidadGuardar = new javax.swing.JTextField();
        txtEmailGuardar = new javax.swing.JTextField();
        txtDireccionGuardar = new javax.swing.JTextField();
        txtColegiadoGuardar = new javax.swing.JTextField();
        separadorGuardar = new javax.swing.JSeparator();
        botonGuardarDoctor = new javax.swing.JButton();

        jTextField5.setText("jTextField1");

        setBackground(new java.awt.Color(22, 156, 160));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        lblIdDoctor.setText("Id Doctor");

        lblNombreDoctor.setText("Nombre Doctor");

        lblApellidoDoctor.setText("Apellido Doctor");

        lblNumeroTelefono.setText("Numero Telefono");

        lblEspecialidad.setText("Especialidad");

        lblEmail.setText("Email");

        lblDireccion.setText("Direccion");

        lblColegiado.setText("Colegiado");

        botonGuardarDoctor.setText("Guardar Doctor");
        botonGuardarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGuardarDoctorLayout = new javax.swing.GroupLayout(panelGuardarDoctor);
        panelGuardarDoctor.setLayout(panelGuardarDoctorLayout);
        panelGuardarDoctorLayout.setHorizontalGroup(
            panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarDoctorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadorGuardar)
                    .addGroup(panelGuardarDoctorLayout.createSequentialGroup()
                        .addComponent(lblColegiado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55)
                        .addComponent(txtColegiadoGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGuardarDoctorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonGuardarDoctor))
                    .addGroup(panelGuardarDoctorLayout.createSequentialGroup()
                        .addGroup(panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGuardarDoctorLayout.createSequentialGroup()
                                .addGroup(panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblIdDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNombreDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblApellidoDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNumeroTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(65, 65, 65))
                            .addGroup(panelGuardarDoctorLayout.createSequentialGroup()
                                .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(panelGuardarDoctorLayout.createSequentialGroup()
                                .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(56, 56, 56)))
                        .addGroup(panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionGuardar)
                            .addComponent(txtEmailGuardar)
                            .addGroup(panelGuardarDoctorLayout.createSequentialGroup()
                                .addGroup(panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdDoctorGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtNombreDoctorGuardar)
                                    .addComponent(txtApellidoDoctorGuardar)
                                    .addComponent(txtNumeroTelefonoGuardar)
                                    .addComponent(txtEspecialidadGuardar))
                                .addGap(0, 2, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelGuardarDoctorLayout.setVerticalGroup(
            panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarDoctorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdDoctorGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdDoctor))
                .addGap(4, 4, 4)
                .addGroup(panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreDoctor)
                    .addComponent(txtNombreDoctorGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoDoctor)
                    .addComponent(txtApellidoDoctorGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroTelefono)
                    .addComponent(txtNumeroTelefonoGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecialidad)
                    .addComponent(txtEspecialidadGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmailGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccionGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGuardarDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColegiado)
                    .addComponent(txtColegiadoGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separadorGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGuardarDoctor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGuardarDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGuardarDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarDoctorActionPerformed
        /**
     * instancia nueva
     */
// TODO add your handling code here:
        Doctor doctor = new Doctor();
        doctor.setId(Integer.parseInt(txtIdDoctorGuardar.getText()));
        doctor.setNombre(txtNombreDoctorGuardar.getText());
        doctor.setApellido(txtApellidoDoctorGuardar.getText());
        doctor.setNumero(Integer.parseInt(txtNumeroTelefonoGuardar.getText()));
        doctor.setEspecialidad(txtEspecialidadGuardar.getText());
        doctor.setEmail(txtEmailGuardar.getText());
        doctor.setDireccion(txtDireccionGuardar.getText());
        doctor.setColegiado(Integer.parseInt(txtColegiadoGuardar.getText()));
        
        controlador.agregarDoctor(doctor);
        
        txtIdDoctorGuardar.setText("");
        txtNombreDoctorGuardar.setText("");
        txtApellidoDoctorGuardar.setText("");
        txtNumeroTelefonoGuardar.setText("");
        txtEspecialidadGuardar.setText("");
        txtEmailGuardar.setText("");
        txtDireccionGuardar.setText("");
        txtColegiadoGuardar.setText("");
        
        setVisible(false);
    }//GEN-LAST:event_botonGuardarDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarDoctor;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblApellidoDoctor;
    private javax.swing.JLabel lblColegiado;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblIdDoctor;
    private javax.swing.JLabel lblNombreDoctor;
    private javax.swing.JLabel lblNumeroTelefono;
    private javax.swing.JPanel panelGuardarDoctor;
    private javax.swing.JSeparator separadorGuardar;
    private javax.swing.JTextField txtApellidoDoctorGuardar;
    private javax.swing.JTextField txtColegiadoGuardar;
    private javax.swing.JTextField txtDireccionGuardar;
    private javax.swing.JTextField txtEmailGuardar;
    private javax.swing.JTextField txtEspecialidadGuardar;
    private javax.swing.JTextField txtIdDoctorGuardar;
    private javax.swing.JTextField txtNombreDoctorGuardar;
    private javax.swing.JTextField txtNumeroTelefonoGuardar;
    // End of variables declaration//GEN-END:variables
}
