/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;
import org.ricardocolindres.modelo.Cliente;
import org.ricardocolindres.controlador.ControlCliente;

/**
 * Clase que contiene la Vista de Ver Clientes
 * @author Ricardo Adrian Colindres Franco
 * @version  1.0
 * @see Cliente
 * @see ControlCliente
 */
public class VistaVerClientes extends javax.swing.JInternalFrame {
    /**
     * instancias nuevas
     */

    public ControlCliente controlador = ControlCliente.getInstancia();  
    /**
     * Creates new form VistaVerClientes
     */
    public VistaVerClientes() {
        initComponents();
    }
    
    public void mostrarDatosCliente(){
        /**
         * obtener los datos
         */
        String [] encabezados = {"Id Cliente", "Nombre Cliente", "Apellido Cliente", "Numero Cliente", "Email Cliente", "Cliente Duenio"};
        int cantidadDeClientes = controlador.cantidadDeClientes();
        
        DefaultTableModel cabecera = new DefaultTableModel(encabezados, cantidadDeClientes);
        tablaDeClientes.setModel(cabecera);
        TableModel listaDeClientes = tablaDeClientes.getModel();
        
        for(int i=0; i<cantidadDeClientes;i++){
            Cliente cliente = new Cliente();
            cliente = controlador.listaDeClientes().get(i);
            listaDeClientes.setValueAt(cliente.getIdCl(), i, 0);
            listaDeClientes.setValueAt(cliente.getNombreCli(), i, 1);
            listaDeClientes.setValueAt(cliente.getApellidoCli(), i, 2);
            listaDeClientes.setValueAt(cliente.getNombreCli(), i, 3);
            listaDeClientes.setValueAt(cliente.getEmailClie(), i, 4);
            listaDeClientes.setValueAt(cliente.getDuenioClie(), i, 5);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelVerListaClientes = new javax.swing.JScrollPane();
        tablaDeClientes = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        tablaDeClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Cliente", "Nombre Cliente", "Apellido Cliente", "Numero Cliente", "Email Cliente", "Cliente Duenio"
            }
        ));
        scrollPanelVerListaClientes.setViewportView(tablaDeClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelVerListaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelVerListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPanelVerListaClientes;
    private javax.swing.JTable tablaDeClientes;
    // End of variables declaration//GEN-END:variables
}
