/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import org.ricardocolindres.controlador.ControlCita;
import org.ricardocolindres.modelo.Cita;

/**
 * Clase que contiene la Vista de Agregar Cita
 * @author Ricardo Adrian Colindres Franco
 * @version  1.0
 * @see Cita
 * @see ControlCita
 */
public class VistaAgregarCita extends javax.swing.JInternalFrame {
    /**
     * instancia nueva
     */
    ControlCita controlador = ControlCita.getInstancia();   

    /**
     * Creates new form VistaAgregarCita
     */
    public VistaAgregarCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGuardarCita = new javax.swing.JPanel();
        lblIdCitaGuardar = new javax.swing.JLabel();
        lblDiaCitaGuardar = new javax.swing.JLabel();
        lblMesCitaGuardar = new javax.swing.JLabel();
        lblAnioCitaGuardar = new javax.swing.JLabel();
        lblClienteCitaGuardar = new javax.swing.JLabel();
        lblHoraCitaGuardar = new javax.swing.JLabel();
        txtIdCitaGuardar = new javax.swing.JTextField();
        txtDiaCitaGuardar = new javax.swing.JTextField();
        txtMesCitaGuardar = new javax.swing.JTextField();
        txtAnioCitaGuardar = new javax.swing.JTextField();
        txtClienteCitaGuardar = new javax.swing.JTextField();
        txtHoraCitaGuardar = new javax.swing.JTextField();
        separadorGuardarCita = new javax.swing.JSeparator();
        botonGuardarCita = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        lblIdCitaGuardar.setText("Id Cita");

        lblDiaCitaGuardar.setText("Dia Cita");

        lblMesCitaGuardar.setText("Mes Cita");

        lblAnioCitaGuardar.setText("Anio Cita");

        lblClienteCitaGuardar.setText("Cliente Cita");

        lblHoraCitaGuardar.setText("Hora Cita");

        botonGuardarCita.setText("Guardar Cita");
        botonGuardarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGuardarCitaLayout = new javax.swing.GroupLayout(panelGuardarCita);
        panelGuardarCita.setLayout(panelGuardarCitaLayout);
        panelGuardarCitaLayout.setHorizontalGroup(
            panelGuardarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGuardarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGuardarCitaLayout.createSequentialGroup()
                        .addComponent(separadorGuardarCita)
                        .addContainerGap())
                    .addGroup(panelGuardarCitaLayout.createSequentialGroup()
                        .addGroup(panelGuardarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdCitaGuardar)
                            .addComponent(lblDiaCitaGuardar)
                            .addComponent(lblMesCitaGuardar)
                            .addComponent(lblAnioCitaGuardar)
                            .addComponent(lblClienteCitaGuardar)
                            .addComponent(lblHoraCitaGuardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(panelGuardarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDiaCitaGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtIdCitaGuardar)
                            .addComponent(txtMesCitaGuardar)
                            .addComponent(txtAnioCitaGuardar)
                            .addComponent(txtClienteCitaGuardar)
                            .addComponent(txtHoraCitaGuardar))
                        .addGap(16, 16, 16))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGuardarCitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardarCita)
                .addGap(18, 18, 18))
        );
        panelGuardarCitaLayout.setVerticalGroup(
            panelGuardarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGuardarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCitaGuardar)
                    .addComponent(txtIdCitaGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGuardarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaCitaGuardar)
                    .addComponent(txtDiaCitaGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGuardarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMesCitaGuardar)
                    .addComponent(txtMesCitaGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGuardarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnioCitaGuardar)
                    .addComponent(txtAnioCitaGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGuardarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteCitaGuardar)
                    .addComponent(txtClienteCitaGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGuardarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraCitaGuardar)
                    .addComponent(txtHoraCitaGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separadorGuardarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGuardarCita)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGuardarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGuardarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarCitaActionPerformed
         /**
         * obtener todos los datos
         */
// TODO add your handling code here:
        Cita cita = new Cita();
        cita.setId(Integer.parseInt(txtIdCitaGuardar.getText()));
        cita.setDia(Integer.parseInt(txtDiaCitaGuardar.getText()));
        cita.setMes(txtMesCitaGuardar.getText());
        cita.setAnio(Integer.parseInt(txtAnioCitaGuardar.getText()));
        cita.setCliente(txtClienteCitaGuardar.getText());
        cita.setHora(txtHoraCitaGuardar.getText());

        
        controlador.agregarCitas(cita);
        
        txtIdCitaGuardar.setText("");
        txtDiaCitaGuardar.setText("");
        txtMesCitaGuardar.setText("");
        txtAnioCitaGuardar.setText("");
        txtClienteCitaGuardar.setText("");
        txtHoraCitaGuardar.setText("");
        
        setVisible(false);
    }//GEN-LAST:event_botonGuardarCitaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarCita;
    private javax.swing.JLabel lblAnioCitaGuardar;
    private javax.swing.JLabel lblClienteCitaGuardar;
    private javax.swing.JLabel lblDiaCitaGuardar;
    private javax.swing.JLabel lblHoraCitaGuardar;
    private javax.swing.JLabel lblIdCitaGuardar;
    private javax.swing.JLabel lblMesCitaGuardar;
    private javax.swing.JPanel panelGuardarCita;
    private javax.swing.JSeparator separadorGuardarCita;
    private javax.swing.JTextField txtAnioCitaGuardar;
    private javax.swing.JTextField txtClienteCitaGuardar;
    private javax.swing.JTextField txtDiaCitaGuardar;
    private javax.swing.JTextField txtHoraCitaGuardar;
    private javax.swing.JTextField txtIdCitaGuardar;
    private javax.swing.JTextField txtMesCitaGuardar;
    // End of variables declaration//GEN-END:variables
}
