/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.ricardocolindres.vista;
import org.ricardocolindres.controlador.ControlMascota;
import org.ricardocolindres.modelo.Mascota;

/**
 * Clase que contiene la Vista de Actualizar Mascota
 * @author Ricardo Adrian Colindres Franco
 * @version  1.0
 * @see Mascota
 * @see ControlMascota 
 */
public class VistaActualizarMascota extends javax.swing.JInternalFrame {
    /**
     * instancias nuevas
     */
    Mascota mascotaAntiguo = new Mascota();
    Mascota maascotaActualizado = new Mascota();
    ControlMascota controlador = ControlMascota.getInstancia();

    /**
     * Creates new form VistaActualizarMascota
     */
    public VistaActualizarMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActualizarMascota = new javax.swing.JPanel();
        lblIdMascotaActualizar = new javax.swing.JLabel();
        lblNombreMascotaActualizar = new javax.swing.JLabel();
        lblDuenioMascotaActualizar = new javax.swing.JLabel();
        lblEspecieMascotaActualizar = new javax.swing.JLabel();
        lblRazaMascotaActualizar = new javax.swing.JLabel();
        txtIdMascotaActualizar = new javax.swing.JTextField();
        txtNombreMascotaActualizar = new javax.swing.JTextField();
        txtDuenioMascotaActualizar = new javax.swing.JTextField();
        txtEspecieMascotaActualizar = new javax.swing.JTextField();
        txtRazaMascotaActualizar = new javax.swing.JTextField();
        separadorMascotaActualizar = new javax.swing.JSeparator();
        botonActualizarMascota = new javax.swing.JButton();
        separadorBuscarIdMascotaActualizar = new javax.swing.JSeparator();
        lblBuscarIdMascotaActualizar = new javax.swing.JLabel();
        txtBuscarIdMascotaActualizar = new javax.swing.JTextField();
        botonBuscarMascotaActualizar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        lblIdMascotaActualizar.setText("Id Mascota");

        lblNombreMascotaActualizar.setText("Nombre Mascota");

        lblDuenioMascotaActualizar.setText("Duenio Mascota");

        lblEspecieMascotaActualizar.setText("Especie Mascota");

        lblRazaMascotaActualizar.setText("Raza Mascota");

        botonActualizarMascota.setText("Actualizar Datos");
        botonActualizarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarMascotaActionPerformed(evt);
            }
        });

        lblBuscarIdMascotaActualizar.setText("Buscar Id Mascota Actualizar");

        botonBuscarMascotaActualizar.setText("Buscar");
        botonBuscarMascotaActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarMascotaActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActualizarMascotaLayout = new javax.swing.GroupLayout(panelActualizarMascota);
        panelActualizarMascota.setLayout(panelActualizarMascotaLayout);
        panelActualizarMascotaLayout.setHorizontalGroup(
            panelActualizarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarMascotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActualizarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelActualizarMascotaLayout.createSequentialGroup()
                        .addComponent(separadorMascotaActualizar)
                        .addContainerGap())
                    .addGroup(panelActualizarMascotaLayout.createSequentialGroup()
                        .addGroup(panelActualizarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelActualizarMascotaLayout.createSequentialGroup()
                                .addComponent(lblRazaMascotaActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRazaMascotaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelActualizarMascotaLayout.createSequentialGroup()
                                .addComponent(lblEspecieMascotaActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEspecieMascotaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelActualizarMascotaLayout.createSequentialGroup()
                                .addComponent(lblDuenioMascotaActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDuenioMascotaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelActualizarMascotaLayout.createSequentialGroup()
                                .addComponent(lblNombreMascotaActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombreMascotaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelActualizarMascotaLayout.createSequentialGroup()
                                .addComponent(lblIdMascotaActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdMascotaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarMascotaLayout.createSequentialGroup()
                        .addGroup(panelActualizarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarMascotaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonActualizarMascota))
                            .addComponent(separadorBuscarIdMascotaActualizar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(panelActualizarMascotaLayout.createSequentialGroup()
                        .addComponent(lblBuscarIdMascotaActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarIdMascotaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
            .addGroup(panelActualizarMascotaLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(botonBuscarMascotaActualizar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelActualizarMascotaLayout.setVerticalGroup(
            panelActualizarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarMascotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActualizarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdMascotaActualizar)
                    .addComponent(txtIdMascotaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreMascotaActualizar)
                    .addComponent(txtNombreMascotaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuenioMascotaActualizar)
                    .addComponent(txtDuenioMascotaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecieMascotaActualizar)
                    .addComponent(txtEspecieMascotaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazaMascotaActualizar)
                    .addComponent(txtRazaMascotaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separadorMascotaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonActualizarMascota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separadorBuscarIdMascotaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActualizarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarIdMascotaActualizar)
                    .addComponent(txtBuscarIdMascotaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(botonBuscarMascotaActualizar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelActualizarMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelActualizarMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarMascotaActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarMascotaActualizarActionPerformed
        /**
         * obtener todos los datos
         */
// TODO add your handling code here:
        mascotaAntiguo = controlador.buscarMascota(Integer.parseInt(txtBuscarIdMascotaActualizar.getText()));
        txtIdMascotaActualizar.setText(String.valueOf(mascotaAntiguo.getId()));
        txtNombreMascotaActualizar.setText(mascotaAntiguo.getNombre());
        txtDuenioMascotaActualizar.setText(mascotaAntiguo.getDuenio());
        txtEspecieMascotaActualizar.setText(String.valueOf(mascotaAntiguo.getEspecie()));
        txtRazaMascotaActualizar.setText(mascotaAntiguo.getRaza());
        
    }//GEN-LAST:event_botonBuscarMascotaActualizarActionPerformed

    private void botonActualizarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarMascotaActionPerformed
           // TODO add your handling code here:
        maascotaActualizado.setId(Integer.parseInt(txtIdMascotaActualizar.getText()));
        maascotaActualizado.setNombre(txtNombreMascotaActualizar.getText());
        maascotaActualizado.setDuenio(txtDuenioMascotaActualizar.getText());
        maascotaActualizado.setEspecie(txtEspecieMascotaActualizar.getText());
        maascotaActualizado.setRaza(txtRazaMascotaActualizar.getText());
        controlador.actualizarMascota(mascotaAntiguo, maascotaActualizado);
        setVisible(false);
        
    }//GEN-LAST:event_botonActualizarMascotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarMascota;
    private javax.swing.JButton botonBuscarMascotaActualizar;
    private javax.swing.JLabel lblBuscarIdMascotaActualizar;
    private javax.swing.JLabel lblDuenioMascotaActualizar;
    private javax.swing.JLabel lblEspecieMascotaActualizar;
    private javax.swing.JLabel lblIdMascotaActualizar;
    private javax.swing.JLabel lblNombreMascotaActualizar;
    private javax.swing.JLabel lblRazaMascotaActualizar;
    private javax.swing.JPanel panelActualizarMascota;
    private javax.swing.JSeparator separadorBuscarIdMascotaActualizar;
    private javax.swing.JSeparator separadorMascotaActualizar;
    private javax.swing.JTextField txtBuscarIdMascotaActualizar;
    private javax.swing.JTextField txtDuenioMascotaActualizar;
    private javax.swing.JTextField txtEspecieMascotaActualizar;
    private javax.swing.JTextField txtIdMascotaActualizar;
    private javax.swing.JTextField txtNombreMascotaActualizar;
    private javax.swing.JTextField txtRazaMascotaActualizar;
    // End of variables declaration//GEN-END:variables
}
